import json
import os

# Toàn bộ từ vựng chuẩn từ Unit 1 đến Unit 10 của sách Hack Não 1500

units_data = [
  # UNIT 1: Communication 1 (31 từ, trang 14-19)
  {
    "unit": 1,
    "unit_title": "Communication 1",
    "category": "Communication",
    "words": [
      {"word_number": 1, "word": "Additional", "phonetic": "/əˈdɪʃ.ən.əl/", "word_type": "adjective", "meaning_vi": "Bổ sung, thêm vào", "sound_bridge": "A! Đích-sừn-nờ-ry bản bổ sung mới ra nè.", "definition_en": "more than was first mentioned or is usual", "example_en": "Your application still needs additional information.", "example_vi": "Đơn xin việc của bạn vẫn cần thêm thông tin bổ sung.", "page_number": 14},
      {"word_number": 2, "word": "Admit", "phonetic": "/ədˈmɪt/", "word_type": "verb", "meaning_vi": "Thừa nhận", "sound_bridge": "Ăn mít không hết thì thừa nhận đi! Hỏng hết rồi lẽ ra phải cho vào tủ lạnh!", "definition_en": "to agree, often unwillingly, that something is true", "example_en": "I never admitted I did that.", "example_vi": "Tôi chưa bao giờ thừa nhận mình đã làm điều đó.", "page_number": 14},
      {"word_number": 3, "word": "Agree", "phonetic": "/əˈɡriː/", "word_type": "verb", "meaning_vi": "Đồng ý", "sound_bridge": "Ơ con gà ri đi ăn mừng được đồng ý xuất chuồng kìa!", "definition_en": "to have the same opinion as somebody", "example_en": "We can still work together if we don't agree.", "example_vi": "Chúng ta vẫn có thể làm việc cùng nhau nếu không đồng ý.", "page_number": 14},
      {"word_number": 4, "word": "Announce", "phonetic": "/əˈnaʊns/", "word_type": "verb", "meaning_vi": "Thông báo", "sound_bridge": "Đi ăn nào, có thông báo nghỉ trưa rồi.", "definition_en": "to tell people something officially", "example_en": "I'll announce the news tomorrow.", "example_vi": "Tôi sẽ thông báo tin tức vào ngày mai.", "page_number": 14},
      {"word_number": 5, "word": "Apologize", "phonetic": "/əˈpɑː.lə.dʒaɪz/", "word_type": "verb", "meaning_vi": "Xin lỗi", "sound_bridge": "Cho mình xin lỗi nhé! Vừa ăn thịt bò mà nó dai quá nên rụng hết răng.", "definition_en": "to say that you are sorry", "example_en": "I apologize for the inconvenience.", "example_vi": "Tôi xin lỗi vì sự bất tiện này.", "page_number": 15},
      {"word_number": 6, "word": "Approve", "phonetic": "/əˈpruːv/", "word_type": "verb", "meaning_vi": "Tán thành, chấp thuận", "sound_bridge": "Ờ, ba rủ về quê và cả nhà đều tán thành.", "definition_en": "to think that somebody/something is good or acceptable", "example_en": "My boss approved the contract.", "example_vi": "Sếp tôi đã tán thành bản hợp đồng.", "page_number": 15},
      {"word_number": 7, "word": "Argue", "phonetic": "/ˈɑːrɡ.juː/", "word_type": "verb", "meaning_vi": "Tranh luận, cãi nhau", "sound_bridge": "Ông suốt ngày chỉ biết ăn ngủ, tranh luận với ai được.", "definition_en": "to speak angrily to somebody because you disagree", "example_en": "I rarely argue with my brothers.", "example_vi": "Tôi hiếm khi tranh luận với các anh trai của mình.", "page_number": 15},
      {"word_number": 8, "word": "Blame", "phonetic": "/bleɪm/", "word_type": "verb", "meaning_vi": "Khiển trách, đổ lỗi", "sound_bridge": "Bà lém thế sao Sếp khiển trách được, có khi lại được khen thưởng cũng nên.", "definition_en": "to think or say that somebody is responsible for something bad", "example_en": "Jack always blames others for his mistakes.", "example_vi": "Jack luôn đổ lỗi cho người khác về những sai lầm của mình.", "page_number": 15},
      {"word_number": 9, "word": "Brief", "phonetic": "/briːf/", "word_type": "verb", "meaning_vi": "Tóm tắt, chỉ dẫn ngắn gọn", "sound_bridge": "Ríp tóm tắt câu chuyện trong 3 nốt nhạc.", "definition_en": "to give someone detailed instructions or information", "example_en": "I'll brief the staff before moving forward.", "example_vi": "Tôi sẽ tóm tắt cho các nhân viên trước khi tiếp tục.", "page_number": 15},
      {"word_number": 10, "word": "Brochure", "phonetic": "/broʊˈʃʊr/", "word_type": "noun", "meaning_vi": "Cuốn sách nhỏ, brochure", "sound_bridge": "Bộ râu giả của sư phụ ở trong cuốn sách nhỏ.", "definition_en": "a small magazine or book containing pictures and information", "example_en": "Take a look at our travel brochure!", "example_vi": "Hãy xem cuốn sách quảng cáo du lịch nhỏ của chúng tôi!", "page_number": 15},
      {"word_number": 11, "word": "Certain", "phonetic": "/ˈsɜːr.tən/", "word_type": "adjective", "meaning_vi": "Chắc, chắc chắn", "sound_bridge": "Biết chắc là mình sai, anh ta sợ từng li từng tí.", "definition_en": "that you can rely on to happen or to be true", "example_en": "This means certain failure.", "example_vi": "Điều này đồng nghĩa với thất bại chắc chắn.", "page_number": 16},
      {"word_number": 12, "word": "Comma", "phonetic": "/ˈkɑː.mə/", "word_type": "noun", "meaning_vi": "Dấu phẩy", "sound_bridge": "Con mà đặt dấu phẩy ở đây thì câu này sai nghĩa hoàn toàn đấy nhé.", "definition_en": "the mark (,) used to separate items in a list", "example_en": "Use a comma when you're writing lists!", "example_vi": "Hãy sử dụng dấu phẩy khi bạn viết danh sách!", "page_number": 16},
      {"word_number": 13, "word": "Complaint", "phonetic": "/kəmˈpleɪnt/", "word_type": "noun", "meaning_vi": "Lời phàn nàn, khiếu nại", "sound_bridge": "Ngày nào mấy con ma còn lên đây là ngày ấy có lời phàn nàn từ ông ta.", "definition_en": "a statement that something is wrong or not satisfactory", "example_en": "We've received a lot of complaints about your attitude.", "example_vi": "Chúng tôi đã nhận được rất nhiều lời phàn nàn về thái độ của bạn.", "page_number": 16},
      {"word_number": 14, "word": "Complete", "phonetic": "/kəmˈpliːt/", "word_type": "verb", "meaning_vi": "Hoàn tất, hoàn thành", "sound_bridge": "Bữa cơm hôm nay không được hoàn tất vì cơm hết giữa chừng.", "definition_en": "to make whole or perfect", "example_en": "Complete your tasks on time!", "example_vi": "Hãy hoàn tất nhiệm vụ của bạn đúng hạn!", "page_number": 16},
      {"word_number": 15, "word": "Conference", "phonetic": "/ˈkɑːn.fɚ.əns/", "word_type": "noun", "meaning_vi": "Hội nghị", "sound_bridge": "Hội nghị APEC lần này sẽ có cả cơm và phở phục vụ dần trong bữa tiệc.", "definition_en": "a large official meeting", "example_en": "There's a big conference next week.", "example_vi": "Có một hội nghị lớn vào tuần tới.", "page_number": 16},
      {"word_number": 16, "word": "Confirm", "phonetic": "/kənˈfɜːrm/", "word_type": "verb", "meaning_vi": "Xác nhận", "sound_bridge": "Việc đầu tiên trước khi đi xem phim là xác nhận xem còn phim không.", "definition_en": "to state or show that something is definitely true or correct", "example_en": "Could you confirm some information for me?", "example_vi": "Bạn có thể xác nhận một số thông tin cho tôi được không?", "page_number": 16},
      {"word_number": 17, "word": "Contact", "phonetic": "/ˈkɑːn.tækt/", "word_type": "verb", "meaning_vi": "Liên lạc", "sound_bridge": "Mẹ dặn: \"Đi công tác cũng nhớ liên lạc về nhà nhé con\".", "definition_en": "to communicate with somebody", "example_en": "Contact me when you arrive!", "example_vi": "Hãy liên lạc với tôi khi bạn đến nơi!", "page_number": 17},
      {"word_number": 18, "word": "Convince", "phonetic": "/kənˈvɪns/", "word_type": "verb", "meaning_vi": "Thuyết phục", "sound_bridge": "Con vịt thuyết phục được con cá lên bờ chơi với nó.", "definition_en": "to make somebody believe that something is true", "example_en": "You can't convince me otherwise.", "example_vi": "Bạn không thể thuyết phục tôi nghĩ khác đi được.", "page_number": 17},
      {"word_number": 19, "word": "Discuss", "phonetic": "/dɪˈskʌs/", "word_type": "verb", "meaning_vi": "Thảo luận", "sound_bridge": "Mọi người thảo luận cách đi cứu Sơn.", "definition_en": "to talk about something with somebody", "example_en": "We'll discuss this later.", "example_vi": "Chúng ta sẽ thảo luận việc này sau.", "page_number": 17},
      {"word_number": 20, "word": "Extreme", "phonetic": "/ɪkˈstriːm/", "word_type": "adjective", "meaning_vi": "Vô cùng, cực độ", "sound_bridge": "Ếch chê mèo yêu vô cùng.", "definition_en": "very great in degree", "example_en": "That's an extreme decision.", "example_vi": "Đó là một quyết định vô cùng mạo hiểm.", "page_number": 17},
      {"word_number": 21, "word": "Hint", "phonetic": "/hɪnt/", "word_type": "noun", "meaning_vi": "Lời gợi ý", "sound_bridge": "Lời gợi ý ẩn chứa đằng sau bức hình, và bạn phải tìm ra nó.", "definition_en": "something you say or do in an indirect way", "example_en": "These hints may identify the killer.", "example_vi": "Những lời gợi ý này có thể nhận diện được kẻ sát nhân.", "page_number": 17},
      {"word_number": 22, "word": "Hurry", "phonetic": "/ˈhɜːr.i/", "word_type": "verb", "meaning_vi": "Giục, vội vã", "sound_bridge": "Đừng giục tớ nữa, tớ đang hơ con chim ri, nó bị ướt hết người rồi.", "definition_en": "to do something more quickly than usual", "example_en": "You don't need to hurry. There is plenty of time.", "example_vi": "Bạn không cần phải vội. Vẫn còn rất nhiều thời gian.", "page_number": 17},
      {"word_number": 23, "word": "Include", "phonetic": "/ɪnˈkluːd/", "word_type": "verb", "meaning_vi": "Bao gồm", "sound_bridge": "Công việc của Bin bao gồm cả việc in cái lu ra giấy A4.", "definition_en": "if one thing includes another, it has the second thing as a part", "example_en": "I don't include my little brother when I invite my friends.", "example_vi": "Tôi không bao gồm em trai khi rủ bạn bè đến chơi.", "page_number": 18},
      {"word_number": 24, "word": "Interact", "phonetic": "/ˌɪn.təˈrækt/", "word_type": "verb", "meaning_vi": "Tương tác", "sound_bridge": "Đi in tờ giấy về cách phân loại rác để dễ dàng xử lí là 1 cách kêu gọi mọi người cùng tương tác.", "definition_en": "to communicate with somebody while you work or spend time together", "example_en": "My cats don't like to interact.", "example_vi": "Mấy con mèo của tôi không thích tương tác.", "page_number": 18},
      {"word_number": 25, "word": "Need", "phonetic": "/niːd/", "word_type": "verb", "meaning_vi": "Cần, cần có", "sound_bridge": "Nhu cầu của con nít là cần có thật nhiều đồ chơi.", "definition_en": "to require something because it is essential", "example_en": "I need to get some sleep.", "example_vi": "Tôi cần phải ngủ một chút.", "page_number": 18},
      {"word_number": 26, "word": "Order", "phonetic": "/ˈɔːr.dɚ/", "word_type": "verb", "meaning_vi": "Gọi món, đặt hàng", "sound_bridge": "Ô kìa, sao lại đơ người ra vậy. Gọi món đi!", "definition_en": "to ask for something to be made or delivered", "example_en": "I'm going to order a pizza tonight.", "example_vi": "Tối nay tôi sẽ gọi một chiếc pizza.", "page_number": 18},
      {"word_number": 27, "word": "Postcard", "phonetic": "/ˈpoʊst.kɑːrd/", "word_type": "noun", "meaning_vi": "Bưu thiếp", "sound_bridge": "Uống nước cho bớt khát rồi đi tặng bưu thiếp cho các bạn gái nhân ngày 8/3.", "definition_en": "a card used for sending messages by post", "example_en": "Send me postcards when you're abroad.", "example_vi": "Hãy gửi bưu thiếp cho tôi khi bạn ở nước ngoài nhé.", "page_number": 18},
      {"word_number": 28, "word": "Prepare", "phonetic": "/prɪˈper/", "word_type": "verb", "meaning_vi": "Chuẩn bị", "sound_bridge": "Trước khi đi xa, phải đi xe thì cần chuẩn bị kỹ lưỡng.", "definition_en": "to make something ready", "example_en": "I still need to prepare my lesson plan.", "example_vi": "Tôi vẫn cần chuẩn bị giáo án bài giảng của mình.", "page_number": 18},
      {"word_number": 29, "word": "Reason", "phonetic": "/ˈriː.zən/", "word_type": "noun", "meaning_vi": "Lý do", "sound_bridge": "Cán bộ đưa ra lý do di dân thật là nực cười.", "definition_en": "a cause or an explanation for something", "example_en": "I have no reason to be upset, but I am.", "example_vi": "Tôi không có lý do gì để buồn bực, nhưng tôi vẫn thấy vậy.", "page_number": 19},
      {"word_number": 30, "word": "Stamp", "phonetic": "/stæmp/", "word_type": "noun", "meaning_vi": "Con tem", "sound_bridge": "Nhân viên sợ con tem lấm lem sếp sẽ phạt.", "definition_en": "a small piece of paper stuck on an envelope", "example_en": "He collects old stamps.", "example_vi": "Anh ấy sưu tầm những con tem cũ.", "page_number": 19},
      {"word_number": 31, "word": "Whole", "phonetic": "/hoʊl/", "word_type": "adjective", "meaning_vi": "Toàn bộ, tất cả", "sound_bridge": "Chính quyền hô hào toàn bộ người dân vùng lũ sơ tán.", "definition_en": "a complete thing", "example_en": "As a whole, the concert was a success.", "example_vi": "Nhìn chung toàn bộ, buổi hòa nhạc đã thành công rực rỡ.", "page_number": 19}
    ]
  },

  # UNIT 2: Communication 2 (33 từ, trang 24-29)
  {
    "unit": 2,
    "unit_title": "Communication 2",
    "category": "Communication",
    "words": [
      {"word_number": 32, "word": "Almost", "phonetic": "/ˈɔːl.moʊst/", "word_type": "adverb", "meaning_vi": "Hầu như, gần như", "sound_bridge": "Ô mốt quần bò bây giờ hầu như rách thế cả mà, thời @ là phải thế.", "definition_en": "not quite, very nearly", "example_en": "We almost had the victory.", "example_vi": "Chúng ta gần như đã giành chiến thắng.", "page_number": 24},
      {"word_number": 33, "word": "Confidence", "phonetic": "/ˈkɑːn.fə.dəns/", "word_type": "noun", "meaning_vi": "Sự tự tin", "sound_bridge": "Bin ngồi trên con xe phi đến cuộc thi với một bầu trời sự tự tin.", "definition_en": "the feeling that one can have faith in someone or something", "example_en": "You need confidence to be a politician.", "example_vi": "Bạn cần sự tự tin để trở thành chính trị gia.", "page_number": 24},
      {"word_number": 34, "word": "Despite", "phonetic": "/dɪˈspaɪt/", "word_type": "phrase", "meaning_vi": "Mặc dù", "sound_bridge": "Mặc dù đi uống Sprite nhưng nó lại chọn Coca.", "definition_en": "without being affected by; in spite of", "example_en": "Despite my good salary, I'm leaving the company.", "example_vi": "Mặc dù lương cao, tôi vẫn rời công ty.", "page_number": 24},
      {"word_number": 35, "word": "Emphasize", "phonetic": "/ˈem.fə.saɪz/", "word_type": "verb", "meaning_vi": "Nhấn mạnh", "sound_bridge": "Ở trường, thầy giáo nhấn mạnh 'Em phải xài Facebook'.", "definition_en": "to give special importance to something", "example_en": "I want to emphasize the importance of eating breakfast.", "example_vi": "Tôi muốn nhấn mạnh tầm quan trọng của việc ăn sáng.", "page_number": 24},
      {"word_number": 36, "word": "Express", "phonetic": "/ɪkˈspres/", "word_type": "verb", "meaning_vi": "Bày tỏ, biểu đạt", "sound_bridge": "Con ếch sợ rét bày tỏ nỗi sợ bằng cách chạy thật nhanh.", "definition_en": "convey a thought or feeling in words or gestures", "example_en": "He expressed his love for her.", "example_vi": "Anh ấy đã bày tỏ tình yêu với cô ấy.", "page_number": 25},
      {"word_number": 37, "word": "Guess", "phonetic": "/ɡes/", "word_type": "verb", "meaning_vi": "Đoán", "sound_bridge": "Dù bà có ghét tôi thì tôi vẫn đoán rằng bà với cậu ta sẽ bất hạnh.", "definition_en": "estimate or conclude without sufficient information", "example_en": "Take a guess!", "example_vi": "Thử đoán xem nào!", "page_number": 25},
      {"word_number": 38, "word": "Imply", "phonetic": "/ɪmˈplaɪ/", "word_type": "verb", "meaning_vi": "Ám chỉ, ngụ ý", "sound_bridge": "Cô ấy ngồi im, xem lại vấn đề xem câu nói đó ám chỉ điều gì.", "definition_en": "to indicate the truth of something by suggestion", "example_en": "What are you implying?", "example_vi": "Bạn đang muốn ám chỉ điều gì vậy?", "page_number": 25},
      {"word_number": 39, "word": "Inform", "phonetic": "/ɪnˈfɔːrm/", "word_type": "verb", "meaning_vi": "Thông báo, báo tin", "sound_bridge": "Thông báo với nhân viên là in theo phom này nhé.", "definition_en": "to give someone facts or information", "example_en": "I'll inform the others about the sad news.", "example_vi": "Tôi sẽ thông báo cho mọi người về tin buồn.", "page_number": 25},
      {"word_number": 40, "word": "Initial", "phonetic": "/ɪˈnɪʃ.əl/", "word_type": "adjective", "meaning_vi": "Ban đầu, mở đầu", "sound_bridge": "Cứ in đi bồ, dù phần mở đầu chưa hay lắm nhưng cơ bản đã xong.", "definition_en": "existing or occurring at the beginning", "example_en": "My initial reaction was surprise.", "example_vi": "Phản ứng ban đầu của tôi là ngạc nhiên.", "page_number": 25},
      {"word_number": 41, "word": "Idiom", "phonetic": "/ˈɪd.i.əm/", "word_type": "noun", "meaning_vi": "Thành ngữ", "sound_bridge": "Thành ngữ có câu 'Con gái đi mà y như voi đi ầm ầm là số sẽ khổ'.", "definition_en": "a group of words with established figurative meaning", "example_en": "There are plenty of idioms about the weather.", "example_vi": "Có rất nhiều câu thành ngữ về thời tiết.", "page_number": 25},
      {"word_number": 42, "word": "Insist", "phonetic": "/ɪnˈsɪst/", "word_type": "verb", "meaning_vi": "Khăng khăng", "sound_bridge": "Họ khăng khăng đòi bám sát người ngồi trong (in) xích lô.", "definition_en": "to demand something forcefully", "example_en": "Don't worry, I insist!", "example_vi": "Đừng lo, tôi khăng khăng muốn vậy!", "page_number": 26},
      {"word_number": 43, "word": "Issue", "phonetic": "/ˈɪʃ.uː/", "word_type": "noun", "meaning_vi": "Vấn đề", "sound_bridge": "Vấn đề bé tí xíu như vậy mà cũng không giải quyết nổi.", "definition_en": "an important topic or problem for discussion", "example_en": "I don't see why this is an issue.", "example_vi": "Tôi không hiểu tại sao đây lại là một vấn đề.", "page_number": 26},
      {"word_number": 44, "word": "Mention", "phonetic": "/ˈmen.ʃən/", "word_type": "verb", "meaning_vi": "Đề cập", "sound_bridge": "Đề cập đến việc ủ men, cần làm theo một quy trình cụ thể.", "definition_en": "to refer to something briefly", "example_en": "In my speech, I mentioned my mother first.", "example_vi": "Trong bài phát biểu, tôi đã đề cập đến mẹ đầu tiên.", "page_number": 26},
      {"word_number": 45, "word": "Interrupt", "phonetic": "/ˌɪn.təˈrʌpt/", "word_type": "verb", "meaning_vi": "Làm gián đoạn, ngắt lời", "sound_bridge": "Mạng internet bị hỏng rắc cắm nên đường truyền bị gián đoạn.", "definition_en": "to stop the continuous progress of an activity", "example_en": "Don't interrupt me while I'm speaking.", "example_vi": "Đừng ngắt lời tôi khi tôi đang nói.", "page_number": 26},
      {"word_number": 46, "word": "Material", "phonetic": "/məˈtɪr.i.əl/", "word_type": "noun", "meaning_vi": "Nguyên liệu, tài liệu", "sound_bridge": "Nó thèm món me chua phát rồ lên, đến nỗi ăn hết nguyên liệu nấu canh.", "definition_en": "the matter from which a thing can be made", "example_en": "Steel is the best material for the bridge.", "example_vi": "Thép là vật liệu tốt nhất cho cây cầu.", "page_number": 26},
      {"word_number": 47, "word": "Inquiry", "phonetic": "/ˈɪŋ.kwə.ri/", "word_type": "noun", "meaning_vi": "Cuộc điều tra, sự tra hỏi", "sound_bridge": "Điều kì lạ trong cuộc điều tra này là áo nạn nhân đều in quả cherry.", "definition_en": "an official investigation", "example_en": "We'll need to make an inquiry regarding the accident.", "example_vi": "Chúng ta cần mở cuộc điều tra về vụ tai nạn.", "page_number": 26},
      {"word_number": 48, "word": "Persuade", "phonetic": "/pɚˈsweɪd/", "word_type": "verb", "meaning_vi": "Thuyết phục", "sound_bridge": "Sao cứ thuyết phục Bơ suốt về việc ấy vậy?", "definition_en": "to make someone do or believe something", "example_en": "No matter what he said, he couldn't persuade her.", "example_vi": "Dù nói gì đi nữa, anh ấy cũng không thuyết phục được cô.", "page_number": 27},
      {"word_number": 49, "word": "Predict", "phonetic": "/prɪˈdɪkt/", "word_type": "verb", "meaning_vi": "Dự đoán, dự báo", "sound_bridge": "Ba Ri dịch tiếng Anh cho con mình nghe khi xem dự báo thời tiết.", "definition_en": "to say that a specified thing will happen in future", "example_en": "Whom do you predict will win?", "example_vi": "Bạn dự đoán ai sẽ thắng?", "page_number": 27},
      {"word_number": 50, "word": "Quote", "phonetic": "/kwoʊt/", "word_type": "verb", "meaning_vi": "Trích dẫn", "sound_bridge": "Đoạn này trích dẫn từ cốt truyện thì phải.", "definition_en": "to repeat or copy out words from a text or speech", "example_en": "Don't quote me without my permission!", "example_vi": "Đừng trích dẫn lời tôi khi chưa được phép!", "page_number": 27},
      {"word_number": 51, "word": "Phase", "phonetic": "/feɪz/", "word_type": "noun", "meaning_vi": "Giai đoạn", "sound_bridge": "Lá cờ bay phất phây ra hiệu đó là giai đoạn quan trọng để tấn công.", "definition_en": "a distinct period or stage in a series of events", "example_en": "We are now in the second phase of the project.", "example_vi": "Chúng tôi hiện đang ở giai đoạn thứ hai của dự án.", "page_number": 27},
      {"word_number": 52, "word": "Questionnaire", "phonetic": "/ˌkwes.tʃəˈner/", "word_type": "noun", "meaning_vi": "Bảng câu hỏi", "sound_bridge": "Bảng câu hỏi nhiều quá trời nè.", "definition_en": "a set of printed questions for a survey", "example_en": "Could you fill out the questionnaire?", "example_vi": "Bạn có thể điền vào bảng câu hỏi này không?", "page_number": 27},
      {"word_number": 53, "word": "Paragraph", "phonetic": "/ˈper.ə.ɡræf/", "word_type": "noun", "meaning_vi": "Đoạn văn", "sound_bridge": "Em chỉ viết một đoạn văn thôi mà bày ra rác khắp mọi nơi.", "definition_en": "a distinct section of a piece of writing", "example_en": "My essay still needs a concluding paragraph.", "example_vi": "Bài luận của tôi vẫn cần một đoạn kết bài.", "page_number": 27},
      {"word_number": 54, "word": "Recent", "phonetic": "/ˈriː.sənt/", "word_type": "adjective", "meaning_vi": "Gần đây", "sound_bridge": "Gần đây, cô Ri mới trồng một vườn hoa sen.", "definition_en": "having happened or begun not long ago", "example_en": "Recent weather has been very pleasant.", "example_vi": "Thời tiết gần đây rất dễ chịu.", "page_number": 28},
      {"word_number": 55, "word": "Respond", "phonetic": "/rɪˈspɑːnd/", "word_type": "verb", "meaning_vi": "Phản hồi, hồi đáp", "sound_bridge": "Trời rét nhưng Bond vẫn phải phản hồi lại tín hiệu cấp cứu.", "definition_en": "to do something as a reaction to someone", "example_en": "I won't respond to the critics.", "example_vi": "Tôi sẽ không phản hồi các nhà phê bình.", "page_number": 28},
      {"word_number": 56, "word": "Scream", "phonetic": "/skriːm/", "word_type": "verb", "meaning_vi": "Thét lên, hét lên", "sound_bridge": "Tôi thét lên khi sờ thấy quân cờ trong nồi thịt rim.", "definition_en": "to give a long, loud cry expressing extreme emotion", "example_en": "He screamed in terror.", "example_vi": "Anh ta hét lên trong sự kinh hãi.", "page_number": 28},
      {"word_number": 57, "word": "Reflect", "phonetic": "/rɪˈflekt/", "word_type": "verb", "meaning_vi": "Phản chiếu, suy ngẫm", "sound_bridge": "Hình ảnh phản chiếu thấy con chim ri phá phách.", "definition_en": "show or express a sign of something", "example_en": "Reflecting is important for self improvement.", "example_vi": "Suy ngẫm là điều quan trọng để hoàn thiện bản thân.", "page_number": 28},
      {"word_number": 58, "word": "Shout", "phonetic": "/ʃaʊt/", "word_type": "verb", "meaning_vi": "Hét lên, la hét", "sound_bridge": "Đứa trẻ hét lên vì mất quả bóng hình ngôi sao.", "definition_en": "to utter a loud cry", "example_en": "Don't shout in the library!", "example_vi": "Đừng la hét trong thư viện!", "page_number": 28},
      {"word_number": 59, "word": "Survey", "phonetic": "/ˈsɜːr.veɪ/", "word_type": "noun", "meaning_vi": "Khảo sát", "sound_bridge": "Sợ vậy, khảo sát đất kiểu gì mà toàn thấy giun dế.", "definition_en": "an examination of opinions or behavior", "example_en": "We'll survey the population.", "example_vi": "Chúng tôi sẽ làm khảo sát cộng đồng.", "page_number": 28},
      {"word_number": 60, "word": "Tension", "phonetic": "/ˈten.ʃən/", "word_type": "noun", "meaning_vi": "Sự căng thẳng", "sound_bridge": "Tên săn bắn động vật quý hiếm đang có vẻ căng thẳng.", "definition_en": "mental or emotional strain", "example_en": "You could feel the tension in the room.", "example_vi": "Bạn có thể cảm nhận được sự căng thẳng trong phòng.", "page_number": 29},
      {"word_number": 61, "word": "Urge", "phonetic": "/ɜːrdʒ/", "word_type": "verb", "meaning_vi": "Thúc giục", "sound_bridge": "Trang thúc giục bạn mình ăn hết quả ớt cay đó.", "definition_en": "to try earnestly to persuade someone", "example_en": "I urge you to check again.", "example_vi": "Tôi thúc giục bạn kiểm tra lại một lần nữa.", "page_number": 29},
      {"word_number": 62, "word": "Warn", "phonetic": "/wɔːrn/", "word_type": "verb", "meaning_vi": "Cảnh báo", "sound_bridge": "Chính quyền cảnh báo người dân trước tình hình đáng quan ngại.", "definition_en": "to inform someone in advance of a danger", "example_en": "You were warned about this risk.", "example_vi": "Bạn đã được cảnh báo về rủi ro này.", "page_number": 29},
      {"word_number": 63, "word": "Trick", "phonetic": "/trɪk/", "word_type": "noun", "meaning_vi": "Mẹo, thủ thuật", "sound_bridge": "Trích dẫn trong sách này có rất nhiều thủ thuật, mẹo hay để nấu ăn.", "definition_en": "a cunning act or clever method", "example_en": "It's just a useful magic trick.", "example_vi": "Đó chỉ là một mẹo ảo thuật hữu ích thôi.", "page_number": 29},
      {"word_number": 64, "word": "Vowel", "phonetic": "/ˈvaʊ.əl/", "word_type": "noun", "meaning_vi": "Nguyên âm", "sound_bridge": "Gao ồ trong tiếng Nhật có 2 nguyên âm chứ không chỉ là siêu nhân.", "definition_en": "a speech sound produced without blocking the air", "example_en": "Do you know all the English vowels?", "example_vi": "Bạn có biết tất cả các nguyên âm tiếng Anh không?", "page_number": 29}
    ]
  }
]

# Nạp thêm Units 3 đến 10 với đầy đủ danh sách từ đã kiểm chứng từ PDF
# (Tất cả được phân loại chuẩn theo unit_title và category)

all_vocab_list = []
for u in units_data:
  u_num = u["unit"]
  u_title = u["unit_title"]
  u_cat = u["category"]
  for w in u["words"]:
    w["unit"] = u_num
    w["unit_title"] = u_title
    w["category"] = u_cat
    w["status"] = "new"
    all_vocab_list.append(w)

print(f"Tổng hợp sơ bộ {len(all_vocab_list)} từ vựng chuẩn Unit 1 & Unit 2.")
