import json
import os

# Dữ liệu từ vựng chi tiết từ Unit 1 đến Unit 10 của sách Hack Não 1500

units = [
  # UNIT 1: Communication 1 (31 từ)
  {
    "unit": 1, "unit_title": "Communication 1", "category": "Communication",
    "words": [
      {"word_number": 1, "word": "Additional", "phonetic": "/əˈdɪʃ.ən.əl/", "word_type": "adjective", "meaning_vi": "Bổ sung, thêm vào", "sound_bridge": "A! Đích-sừn-nờ-ry bản bổ sung mới ra nè.", "definition_en": "more than was first mentioned or is usual", "example_en": "Your application still needs additional information.", "example_vi": "Đơn xin việc của bạn vẫn cần thêm thông tin bổ sung.", "page_number": 14},
      {"word_number": 2, "word": "Admit", "phonetic": "/ədˈmɪt/", "word_type": "verb", "meaning_vi": "Thừa nhận", "sound_bridge": "Ăn mít không hết thì thừa nhận đi! Hỏng hết rồi lẽ ra phải cho vào tủ lạnh!", "definition_en": "to agree, often unwillingly, that something is true", "example_en": "I never admitted I did that.", "example_vi": "Tôi chưa bao giờ thừa nhận mình đã làm điều đó.", "page_number": 14},
      {"word_number": 3, "word": "Agree", "phonetic": "/əˈɡriː/", "word_type": "verb", "meaning_vi": "Đồng ý", "sound_bridge": "Ơ con gà ri đi ăn mừng được đồng ý xuất chuồng kìa!", "definition_en": "to have the same opinion as somebody", "example_en": "We can still work together if we don't agree.", "example_vi": "Chúng ta vẫn có thể làm việc cùng nhau nếu không đồng ý.", "page_number": 14},
      {"word_number": 4, "word": "Announce", "phonetic": "/əˈnaʊns/", "word_type": "verb", "meaning_vi": "Thông báo", "sound_bridge": "Đi ăn nào, có thông báo nghỉ trưa rồi.", "definition_en": "to tell people something officially", "example_en": "I'll announce the news tomorrow.", "example_vi": "Tôi sẽ thông báo tin tức vào ngày mai.", "page_number": 14},
      {"word_number": 5, "word": "Apologize", "phonetic": "/əˈpɑː.lə.dʒaɪz/", "word_type": "verb", "meaning_vi": "Xin lỗi", "sound_bridge": "Cho mình xin lỗi nhé! Vừa ăn thịt bò mà nó dai quá nên rụng hết răng.", "definition_en": "to say that you are sorry", "example_en": "I apologize for the inconvenience.", "example_vi": "Tôi xin lỗi vì sự bất tiện này.", "page_number": 15},
      {"word_number": 6, "word": "Approve", "phonetic": "/əˈpruːv/", "word_type": "verb", "meaning_vi": "Tán thành, chấp thuận", "sound_bridge": "Ờ, ba rủ về quê và cả nhà đều tán thành.", "definition_en": "to think that somebody/something is good or acceptable", "example_en": "My boss approved the contract.", "example_vi": "Sếp tôi đã tán thành bản hợp đồng.", "page_number": 15},
      {"word_number": 7, "word": "Argue", "phonetic": "/ˈɑːrɡ.juː/", "word_type": "verb", "meaning_vi": "Tranh luận, cãi nhau", "sound_bridge": "Ông suốt ngày chỉ biết ăn ngủ, tranh luận với ai được.", "definition_en": "to speak angrily to somebody because you disagree", "example_en": "I rarely argue with my brothers.", "example_vi": "Tôi hiếm khi tranh luận với các anh trai của mình.", "page_number": 15},
      {"word_number": 8, "word": "Blame", "phonetic": "/bleɪm/", "word_type": "verb", "meaning_vi": "Khiển trách, đổ lỗi", "sound_bridge": "Bà lém thế sao Sếp khiển trách được, có khi lại được khen thưởng cũng nên.", "definition_en": "to think or say that somebody is responsible for something bad", "example_en": "Jack always blames others for his mistakes.", "example_vi": "Jack luôn đổ lỗi cho người khác về những sai lầm của mình.", "page_number": 15},
      {"word_number": 9, "word": "Brief", "phonetic": "/briːf/", "word_type": "verb", "meaning_vi": "Tóm tắt, chỉ dẫn ngắn gọn", "sound_bridge": "Ríp tóm tắt câu chuyện trong 3 nốt nhạc.", "definition_en": "to give someone detailed instructions or information", "example_en": "I'll brief the staff before moving forward.", "example_vi": "Tôi sẽ tóm tắt cho các nhân viên trước khi tiếp tục.", "page_number": 15},
      {"word_number": 10, "word": "Brochure", "phonetic": "/broʊˈʃʊr/", "word_type": "noun", "meaning_vi": "Cuốn sách nhỏ, brochure", "sound_bridge": "Bộ râu giả của sư phụ ở trong cuốn sách nhỏ.", "definition_en": "a small magazine or book containing pictures and information", "example_en": "Take a look at our travel brochure!", "example_vi": "Hãy xem cuốn sách quảng cáo du lịch nhỏ của chúng tôi!", "page_number": 15},
      {"word_number": 11, "word": "Certain", "phonetic": "/ˈsɜːr.tən/", "word_type": "adjective", "meaning_vi": "Chắc, chắc chắn", "sound_bridge": "Biết chắc là mình sai, anh ta sợ từng li từng tí.", "definition_en": "that you can rely on to happen or to be true", "example_en": "This means certain failure.", "example_vi": "Điều này đồng nghĩa với thất bại chắc chắn.", "page_number": 16},
      {"word_number": 12, "word": "Comma", "phonetic": "/ˈkɑː.mə/", "word_type": "noun", "meaning_vi": "Dấu phẩy", "sound_bridge": "Con mà đặt dấu phẩy ở đây thì câu này sai nghĩa hoàn toàn đấy nhé.", "definition_en": "the mark (,) used to separate items in a list", "example_en": "Use a comma when you're writing lists!", "example_vi": "Hãy sử dụng dấu phẩy khi bạn viết danh sách!", "page_number": 16},
      {"word_number": 13, "word": "Complaint", "phonetic": "/kəmˈpleɪnt/", "word_type": "noun", "meaning_vi": "Lời phàn nàn, khiếu nại", "sound_bridge": "Ngày nào mấy con ma còn lên đây là ngày ấy có lời phàn nàn từ ông ta.", "definition_en": "a statement that something is wrong or not satisfactory", "example_en": "We've received a lot of complaints about your attitude.", "example_vi": "Chúng tôi đã nhận được rất nhiều lời phàn nàn về thái độ của bạn.", "page_number": 16},
      {"word_number": 14, "word": "Complete", "phonetic": "/kəmˈpliːt/", "word_type": "verb", "meaning_vi": "Hoàn tất, hoàn thành", "sound_bridge": "Bữa cơm hôm nay không được hoàn tất vì cơm hết giữa chừng.", "definition_en": "to make whole or perfect", "example_en": "Complete your tasks on time!", "example_vi": "Hãy hoàn tất nhiệm vụ của bạn đúng hạn!", "page_number": 16},
      {"word_number": 15, "word": "Conference", "phonetic": "/ˈkɑːn.fɚ.əns/", "word_type": "noun", "meaning_vi": "Hội nghị", "sound_bridge": "Hội nghị APEC lần này sẽ có cả cơm và phở phục vụ dần trong bữa tiệc.", "definition_en": "a large official meeting", "example_en": "There's a big conference next week.", "example_vi": "Có một hội nghị lớn vào tuần tới.", "page_number": 16},
      {"word_number": 16, "word": "Confirm", "phonetic": "/kənˈfɜːrm/", "word_type": "verb", "meaning_vi": "Xác nhận", "sound_bridge": "Việc đầu tiên trước khi đi xem phim là xác nhận xem còn phim không.", "definition_en": "to state or show that something is definitely true or correct", "example_en": "Could you confirm some information for me?", "example_vi": "Bạn có thể xác nhận một số thông tin cho tôi được không?", "page_number": 16},
      {"word_number": 17, "word": "Contact", "phonetic": "/ˈkɑːn.tækt/", "word_type": "verb", "meaning_vi": "Liên lạc", "sound_bridge": "Mẹ dặn: \"Đi công tác cũng nhớ liên lạc về nhà nhé con\".", "definition_en": "to communicate with somebody", "example_en": "Contact me when you arrive!", "example_vi": "Hãy liên lạc với tôi khi bạn đến nơi!", "page_number": 17},
      {"word_number": 18, "word": "Convince", "phonetic": "/kənˈvɪns/", "word_type": "verb", "meaning_vi": "Thuyết phục", "sound_bridge": "Con vịt thuyết phục được con cá lên bờ chơi với nó.", "definition_en": "to make somebody believe that something is true", "example_en": "You can't convince me otherwise.", "example_vi": "Bạn không thể thuyết phục tôi nghĩ khác đi được.", "page_number": 17},
      {"word_number": 19, "word": "Discuss", "phonetic": "/dɪˈskʌs/", "word_type": "verb", "meaning_vi": "Thảo luận", "sound_bridge": "Mọi người thảo luận cách đi cứu Sơn.", "definition_en": "to talk about something with somebody", "example_en": "We'll discuss this later.", "example_vi": "Chúng ta sẽ thảo luận việc này sau.", "page_number": 17},
      {"word_number": 20, "word": "Extreme", "phonetic": "/ɪkˈstriːm/", "word_type": "adjective", "meaning_vi": "Vô cùng, cực độ", "sound_bridge": "Ếch chê mèo yêu vô cùng.", "definition_en": "very great in degree", "example_en": "That's an extreme decision.", "example_vi": "Đó là một quyết định vô cùng mạo hiểm.", "page_number": 17},
      {"word_number": 21, "word": "Hint", "phonetic": "/hɪnt/", "word_type": "noun", "meaning_vi": "Lời gợi ý", "sound_bridge": "Lời gợi ý ẩn chứa đằng sau bức hình, và bạn phải tìm ra nó.", "definition_en": "something you say or do in an indirect way", "example_en": "These hints may identify the killer.", "example_vi": "Những lời gợi ý này có thể nhận diện được kẻ sát nhân.", "page_number": 17},
      {"word_number": 22, "word": "Hurry", "phonetic": "/ˈhɜːr.i/", "word_type": "verb", "meaning_vi": "Giục, vội vã", "sound_bridge": "Đừng giục tớ nữa, tớ đang hơ con chim ri, nó bị ướt hết người rồi.", "definition_en": "to do something more quickly than usual", "example_en": "You don't need to hurry. There is plenty of time.", "example_vi": "Bạn không cần phải vội. Vẫn còn rất nhiều thời gian.", "page_number": 17},
      {"word_number": 23, "word": "Include", "phonetic": "/ɪnˈkluːd/", "word_type": "verb", "meaning_vi": "Bao gồm", "sound_bridge": "Công việc của Bin bao gồm cả việc in cái lu ra giấy A4.", "definition_en": "if one thing includes another, it has the second thing as a part", "example_en": "I don't include my little brother when I invite my friends.", "example_vi": "Tôi không bao gồm em trai khi rủ bạn bè đến chơi.", "page_number": 18},
      {"word_number": 24, "word": "Interact", "phonetic": "/ˌɪn.təˈrækt/", "word_type": "verb", "meaning_vi": "Tương tác", "sound_bridge": "Đi in tờ giấy về cách phân loại rác để dễ dàng xử lí là 1 cách kêu gọi mọi người cùng tương tác.", "definition_en": "to communicate with somebody while you work or spend time together", "example_en": "My cats don't like to interact.", "example_vi": "Mấy con mèo của tôi không thích tương tác.", "page_number": 18},
      {"word_number": 25, "word": "Need", "phonetic": "/niːd/", "word_type": "verb", "meaning_vi": "Cần, cần có", "sound_bridge": "Nhu cầu của con nít là cần có thật nhiều đồ chơi.", "definition_en": "to require something because it is essential", "example_en": "I need to get some sleep.", "example_vi": "Tôi cần phải ngủ một chút.", "page_number": 18},
      {"word_number": 26, "word": "Order", "phonetic": "/ˈɔːr.dɚ/", "word_type": "verb", "meaning_vi": "Gọi món, đặt hàng", "sound_bridge": "Ô kìa, sao lại đơ người ra vậy. Gọi món đi!", "definition_en": "to ask for something to be made or delivered", "example_en": "I'm going to order a pizza tonight.", "example_vi": "Tối nay tôi sẽ gọi một chiếc pizza.", "page_number": 18},
      {"word_number": 27, "word": "Postcard", "phonetic": "/ˈpoʊst.kɑːrd/", "word_type": "noun", "meaning_vi": "Bưu thiếp", "sound_bridge": "Uống nước cho bớt khát rồi đi tặng bưu thiếp cho các bạn gái nhân ngày 8/3.", "definition_en": "a card used for sending messages by post", "example_en": "Send me postcards when you're abroad.", "example_vi": "Hãy gửi bưu thiếp cho tôi khi bạn ở nước ngoài nhé.", "page_number": 18},
      {"word_number": 28, "word": "Prepare", "phonetic": "/prɪˈper/", "word_type": "verb", "meaning_vi": "Chuẩn bị", "sound_bridge": "Trước khi đi xa, phải đi xe thì cần chuẩn bị kỹ lưỡng.", "definition_en": "to make something ready", "example_en": "I still need to prepare my lesson plan.", "example_vi": "Tôi vẫn cần chuẩn bị giáo án bài giảng của mình.", "page_number": 18},
      {"word_number": 29, "word": "Reason", "phonetic": "/ˈriː.zən/", "word_type": "noun", "meaning_vi": "Lý do", "sound_bridge": "Cán bộ đưa ra lý do di dân thật là nực cười.", "definition_en": "a cause or an explanation for something", "example_en": "I have no reason to be upset, but I am.", "example_vi": "Tôi không có lý do gì để buồn bực, nhưng tôi vẫn thấy vậy.", "page_number": 19},
      {"word_number": 30, "word": "Stamp", "phonetic": "/stæmp/", "word_type": "noun", "meaning_vi": "Con tem", "sound_bridge": "Nhân viên sợ con tem lấm lem sếp sẽ phạt.", "definition_en": "a small piece of paper stuck on an envelope", "example_en": "He collects old stamps.", "example_vi": "Anh ấy sưu tầm những con tem cũ.", "page_number": 19},
      {"word_number": 31, "word": "Whole", "phonetic": "/hoʊl/", "word_type": "adjective", "meaning_vi": "Toàn bộ, tất cả", "sound_bridge": "Chính quyền hô hào toàn bộ người dân vùng lũ sơ tán.", "definition_en": "a complete thing", "example_en": "As a whole, the concert was a success.", "example_vi": "Nhìn chung toàn bộ, buổi hòa nhạc đã thành công rực rỡ.", "page_number": 19}
    ]
  },

  # UNIT 2: Communication 2 (33 từ)
  {
    "unit": 2, "unit_title": "Communication 2", "category": "Communication",
    "words": [
      {"word_number": 32, "word": "Almost", "phonetic": "/ˈɔːl.moʊst/", "word_type": "adverb", "meaning_vi": "Hầu như, gần như", "sound_bridge": "Ô mốt quần bò bây giờ hầu như rách thế cả mà, thời @ là phải thế.", "definition_en": "not quite, very nearly", "example_en": "We almost had the victory.", "example_vi": "Chúng ta gần như đã giành chiến thắng.", "page_number": 24},
      {"word_number": 33, "word": "Confidence", "phonetic": "/ˈkɑːn.fə.dəns/", "word_type": "noun", "meaning_vi": "Sự tự tin", "sound_bridge": "Bin ngồi trên con xe phi đến cuộc thi với một bầu trời sự tự tin.", "definition_en": "the feeling that one can have faith in someone or something", "example_en": "You need confidence to be a politician.", "example_vi": "Bạn cần sự tự tin để trở thành chính trị gia.", "page_number": 24},
      {"word_number": 34, "word": "Despite", "phonetic": "/dɪˈspaɪt/", "word_type": "phrase", "meaning_vi": "Mặc dù", "sound_bridge": "Mặc dù đi uống Sprite nhưng nó lại chọn Coca.", "definition_en": "without being affected by; in spite of", "example_en": "Despite my good salary, I'm leaving the company.", "example_vi": "Mặc dù lương cao, tôi vẫn rời công ty.", "page_number": 24},
      {"word_number": 35, "word": "Emphasize", "phonetic": "/ˈem.fə.saɪz/", "word_type": "verb", "meaning_vi": "Nhấn mạnh", "sound_bridge": "Ở trường, thầy giáo nhấn mạnh 'Em phải xài Facebook'.", "definition_en": "to give special importance to something", "example_en": "I want to emphasize the importance of eating breakfast.", "example_vi": "Tôi muốn nhấn mạnh tầm quan trọng của việc ăn sáng.", "page_number": 24},
      {"word_number": 36, "word": "Express", "phonetic": "/ɪkˈspres/", "word_type": "verb", "meaning_vi": "Bày tỏ, biểu đạt", "sound_bridge": "Con ếch sợ rét bày tỏ nỗi sợ bằng cách chạy thật nhanh.", "definition_en": "convey a thought or feeling in words or gestures", "example_en": "He expressed his love for her.", "example_vi": "Anh ấy đã bày tỏ tình yêu với cô ấy.", "page_number": 25},
      {"word_number": 37, "word": "Guess", "phonetic": "/ɡes/", "word_type": "verb", "meaning_vi": "Đoán", "sound_bridge": "Dù bà có ghét tôi thì tôi vẫn đoán rằng bà với cậu ta sẽ bất hạnh.", "definition_en": "estimate or conclude without sufficient information", "example_en": "Take a guess!", "example_vi": "Thử đoán xem nào!", "page_number": 25},
      {"word_number": 38, "word": "Imply", "phonetic": "/ɪmˈplaɪ/", "word_type": "verb", "meaning_vi": "Ám chỉ, ngụ ý", "sound_bridge": "Cô ấy ngồi im, xem lại vấn đề xem câu nói đó ám chỉ điều gì.", "definition_en": "to indicate the truth of something by suggestion", "example_en": "What are you implying?", "example_vi": "Bạn đang muốn ám chỉ điều gì vậy?", "page_number": 25},
      {"word_number": 39, "word": "Inform", "phonetic": "/ɪnˈfɔːrm/", "word_type": "verb", "meaning_vi": "Thông báo, báo tin", "sound_bridge": "Thông báo với nhân viên là in theo phom này nhé.", "definition_en": "to give someone facts or information", "example_en": "I'll inform the others about the sad news.", "example_vi": "Tôi sẽ thông báo cho mọi người về tin buồn.", "page_number": 25},
      {"word_number": 40, "word": "Initial", "phonetic": "/ɪˈnɪʃ.əl/", "word_type": "adjective", "meaning_vi": "Ban đầu, mở đầu", "sound_bridge": "Cứ in đi bồ, dù phần mở đầu chưa hay lắm nhưng cơ bản đã xong.", "definition_en": "existing or occurring at the beginning", "example_en": "My initial reaction was surprise.", "example_vi": "Phản ứng ban đầu của tôi là ngạc nhiên.", "page_number": 25},
      {"word_number": 41, "word": "Idiom", "phonetic": "/ˈɪd.i.əm/", "word_type": "noun", "meaning_vi": "Thành ngữ", "sound_bridge": "Thành ngữ có câu 'Con gái đi mà y như voi đi ầm ầm là số sẽ khổ'.", "definition_en": "a group of words with established figurative meaning", "example_en": "There are plenty of idioms about the weather.", "example_vi": "Có rất nhiều câu thành ngữ về thời tiết.", "page_number": 25},
      {"word_number": 42, "word": "Insist", "phonetic": "/ɪnˈsɪst/", "word_type": "verb", "meaning_vi": "Khăng khăng", "sound_bridge": "Họ khăng khăng đòi bám sát người ngồi trong (in) xích lô.", "definition_en": "to demand something forcefully", "example_en": "Don't worry, I insist!", "example_vi": "Đừng lo, tôi khăng khăng muốn vậy!", "page_number": 26},
      {"word_number": 43, "word": "Issue", "phonetic": "/ˈɪʃ.uː/", "word_type": "noun", "meaning_vi": "Vấn đề", "sound_bridge": "Vấn đề bé tí xíu như vậy mà cũng không giải quyết nổi.", "definition_en": "an important topic or problem for discussion", "example_en": "I don't see why this is an issue.", "example_vi": "Tôi không hiểu tại sao đây lại là một vấn đề.", "page_number": 26},
      {"word_number": 44, "word": "Mention", "phonetic": "/ˈmen.ʃən/", "word_type": "verb", "meaning_vi": "Đề cập", "sound_bridge": "Đề cập đến việc ủ men, cần làm theo một quy trình cụ thể.", "definition_en": "to refer to something briefly", "example_en": "In my speech, I mentioned my mother first.", "example_vi": "Trong bài phát biểu, tôi đã đề cập đến mẹ đầu tiên.", "page_number": 26},
      {"word_number": 45, "word": "Interrupt", "phonetic": "/ˌɪn.təˈrʌpt/", "word_type": "verb", "meaning_vi": "Làm gián đoạn, ngắt lời", "sound_bridge": "Mạng internet bị hỏng rắc cắm nên đường truyền bị gián đoạn.", "definition_en": "to stop the continuous progress of an activity", "example_en": "Don't interrupt me while I'm speaking.", "example_vi": "Đừng ngắt lời tôi khi tôi đang nói.", "page_number": 26},
      {"word_number": 46, "word": "Material", "phonetic": "/məˈtɪr.i.əl/", "word_type": "noun", "meaning_vi": "Nguyên liệu, tài liệu", "sound_bridge": "Nó thèm món me chua phát rồ lên, đến nỗi ăn hết nguyên liệu nấu canh.", "definition_en": "the matter from which a thing can be made", "example_en": "Steel is the best material for the bridge.", "example_vi": "Thép là vật liệu tốt nhất cho cây cầu.", "page_number": 26},
      {"word_number": 47, "word": "Inquiry", "phonetic": "/ˈɪŋ.kwə.ri/", "word_type": "noun", "meaning_vi": "Cuộc điều tra, sự tra hỏi", "sound_bridge": "Điều kì lạ trong cuộc điều tra này là áo nạn nhân đều in quả cherry.", "definition_en": "an official investigation", "example_en": "We'll need to make an inquiry regarding the accident.", "example_vi": "Chúng ta cần mở cuộc điều tra về vụ tai nạn.", "page_number": 26},
      {"word_number": 48, "word": "Persuade", "phonetic": "/pɚˈsweɪd/", "word_type": "verb", "meaning_vi": "Thuyết phục", "sound_bridge": "Sao cứ thuyết phục Bơ suốt về việc ấy vậy?", "definition_en": "to make someone do or believe something", "example_en": "No matter what he said, he couldn't persuade her.", "example_vi": "Dù nói gì đi nữa, anh ấy cũng không thuyết phục được cô.", "page_number": 27},
      {"word_number": 49, "word": "Predict", "phonetic": "/prɪˈdɪkt/", "word_type": "verb", "meaning_vi": "Dự đoán, dự báo", "sound_bridge": "Ba Ri dịch tiếng Anh cho con mình nghe khi xem dự báo thời tiết.", "definition_en": "to say that a specified thing will happen in future", "example_en": "Whom do you predict will win?", "example_vi": "Bạn dự đoán ai sẽ thắng?", "page_number": 27},
      {"word_number": 50, "word": "Quote", "phonetic": "/kwoʊt/", "word_type": "verb", "meaning_vi": "Trích dẫn", "sound_bridge": "Đoạn này trích dẫn từ cốt truyện thì phải.", "definition_en": "to repeat or copy out words from a text or speech", "example_en": "Don't quote me without my permission!", "example_vi": "Đừng trích dẫn lời tôi khi chưa được phép!", "page_number": 27},
      {"word_number": 51, "word": "Phase", "phonetic": "/feɪz/", "word_type": "noun", "meaning_vi": "Giai đoạn", "sound_bridge": "Lá cờ bay phất phây ra hiệu đó là giai đoạn quan trọng để tấn công.", "definition_en": "a distinct period or stage in a series of events", "example_en": "We are now in the second phase of the project.", "example_vi": "Chúng tôi hiện đang ở giai đoạn thứ hai của dự án.", "page_number": 27},
      {"word_number": 52, "word": "Questionnaire", "phonetic": "/ˌkwes.tʃəˈner/", "word_type": "noun", "meaning_vi": "Bảng câu hỏi", "sound_bridge": "Bảng câu hỏi nhiều quá trời nè.", "definition_en": "a set of printed questions for a survey", "example_en": "Could you fill out the questionnaire?", "example_vi": "Bạn có thể điền vào bảng câu hỏi này không?", "page_number": 27},
      {"word_number": 53, "word": "Paragraph", "phonetic": "/ˈper.ə.ɡræf/", "word_type": "noun", "meaning_vi": "Đoạn văn", "sound_bridge": "Em chỉ viết một đoạn văn thôi mà bày ra rác khắp mọi nơi.", "definition_en": "a distinct section of a piece of writing", "example_en": "My essay still needs a concluding paragraph.", "example_vi": "Bài luận của tôi vẫn cần một đoạn kết bài.", "page_number": 27},
      {"word_number": 54, "word": "Recent", "phonetic": "/ˈriː.sənt/", "word_type": "adjective", "meaning_vi": "Gần đây", "sound_bridge": "Gần đây, cô Ri mới trồng một vườn hoa sen.", "definition_en": "having happened or begun not long ago", "example_en": "Recent weather has been very pleasant.", "example_vi": "Thời tiết gần đây rất dễ chịu.", "page_number": 28},
      {"word_number": 55, "word": "Respond", "phonetic": "/rɪˈspɑːnd/", "word_type": "verb", "meaning_vi": "Phản hồi, hồi đáp", "sound_bridge": "Trời rét nhưng Bond vẫn phải phản hồi lại tín hiệu cấp cứu.", "definition_en": "to do something as a reaction to someone", "example_en": "I won't respond to the critics.", "example_vi": "Tôi sẽ không phản hồi các nhà phê bình.", "page_number": 28},
      {"word_number": 56, "word": "Scream", "phonetic": "/skriːm/", "word_type": "verb", "meaning_vi": "Thét lên, hét lên", "sound_bridge": "Tôi thét lên khi sờ thấy quân cờ trong nồi thịt rim.", "definition_en": "to give a long, loud cry expressing extreme emotion", "example_en": "He screamed in terror.", "example_vi": "Anh ta hét lên trong sự kinh hãi.", "page_number": 28},
      {"word_number": 57, "word": "Reflect", "phonetic": "/rɪˈflekt/", "word_type": "verb", "meaning_vi": "Phản chiếu, suy ngẫm", "sound_bridge": "Hình ảnh phản chiếu thấy con chim ri phá phách.", "definition_en": "show or express a sign of something", "example_en": "Reflecting is important for self improvement.", "example_vi": "Suy ngẫm là điều quan trọng để hoàn thiện bản thân.", "page_number": 28},
      {"word_number": 58, "word": "Shout", "phonetic": "/ʃaʊt/", "word_type": "verb", "meaning_vi": "Hét lên, la hét", "sound_bridge": "Đứa trẻ hét lên vì mất quả bóng hình ngôi sao.", "definition_en": "to utter a loud cry", "example_en": "Don't shout in the library!", "example_vi": "Đừng la hét trong thư viện!", "page_number": 28},
      {"word_number": 59, "word": "Survey", "phonetic": "/ˈsɜːr.veɪ/", "word_type": "noun", "meaning_vi": "Khảo sát", "sound_bridge": "Sợ vậy, khảo sát đất kiểu gì mà toàn thấy giun dế.", "definition_en": "an examination of opinions or behavior", "example_en": "We'll survey the population.", "example_vi": "Chúng tôi sẽ làm khảo sát cộng đồng.", "page_number": 28},
      {"word_number": 60, "word": "Tension", "phonetic": "/ˈten.ʃən/", "word_type": "noun", "meaning_vi": "Sự căng thẳng", "sound_bridge": "Tên săn bắn động vật quý hiếm đang có vẻ căng thẳng.", "definition_en": "mental or emotional strain", "example_en": "You could feel the tension in the room.", "example_vi": "Bạn có thể cảm nhận được sự căng thẳng trong phòng.", "page_number": 29},
      {"word_number": 61, "word": "Urge", "phonetic": "/ɜːrdʒ/", "word_type": "verb", "meaning_vi": "Thúc giục", "sound_bridge": "Trang thúc giục bạn mình ăn hết quả ớt cay đó.", "definition_en": "to try earnestly to persuade someone", "example_en": "I urge you to check again.", "example_vi": "Tôi thúc giục bạn kiểm tra lại một lần nữa.", "page_number": 29},
      {"word_number": 62, "word": "Warn", "phonetic": "/wɔːrn/", "word_type": "verb", "meaning_vi": "Cảnh báo", "sound_bridge": "Chính quyền cảnh báo người dân trước tình hình đáng quan ngại.", "definition_en": "to inform someone in advance of a danger", "example_en": "You were warned about this risk.", "example_vi": "Bạn đã được cảnh báo về rủi ro này.", "page_number": 29},
      {"word_number": 63, "word": "Trick", "phonetic": "/trɪk/", "word_type": "noun", "meaning_vi": "Mẹo, thủ thuật", "sound_bridge": "Trích dẫn trong sách này có rất nhiều thủ thuật, mẹo hay để nấu ăn.", "definition_en": "a cunning act or clever method", "example_en": "It's just a useful magic trick.", "example_vi": "Đó chỉ là một mẹo ảo thuật hữu ích thôi.", "page_number": 29},
      {"word_number": 64, "word": "Vowel", "phonetic": "/ˈvaʊ.əl/", "word_type": "noun", "meaning_vi": "Nguyên âm", "sound_bridge": "Gao ồ trong tiếng Nhật có 2 nguyên âm chứ không chỉ là siêu nhân.", "definition_en": "a speech sound produced without blocking the air", "example_en": "Do you know all the English vowels?", "example_vi": "Bạn có biết tất cả các nguyên âm tiếng Anh không?", "page_number": 29}
    ]
  },

  # UNIT 3: Communication 3 (30 từ, trang 34-39)
  {
    "unit": 3, "unit_title": "Communication 3", "category": "Communication",
    "words": [
      {"word_number": 65, "word": "Address", "phonetic": "/əˈdres/", "word_type": "noun", "meaning_vi": "Địa chỉ, bài diễn văn", "sound_bridge": "Anh đi rét mướt tìm đến đúng địa chỉ nhà em.", "definition_en": "the details of where someone lives", "example_en": "What's your new address?", "example_vi": "Địa chỉ mới của bạn là gì?", "page_number": 34},
      {"word_number": 66, "word": "Advice", "phonetic": "/ədˈvaɪs/", "word_type": "noun", "meaning_vi": "Lời khuyên", "sound_bridge": "Ăn vài trái táo mỗi ngày là lời khuyên hữu ích của bác sĩ.", "definition_en": "guidance or recommendations offered with regard to prudent action", "example_en": "Take my advice and leave early.", "example_vi": "Hãy nghe lời khuyên của tôi và về sớm đi.", "page_number": 34},
      {"word_number": 67, "word": "Annual", "phonetic": "/ˈæn.ju.əl/", "word_type": "adjective", "meaning_vi": "Hàng năm, thường niên", "sound_bridge": "Ăn nhiều bánh chưng trong dịp lễ hàng năm.", "definition_en": "occurring once every year", "example_en": "We host an annual conference.", "example_vi": "Chúng tôi tổ chức hội nghị thường niên hàng năm.", "page_number": 34},
      {"word_number": 68, "word": "Appear", "phonetic": "/əˈpɪr/", "word_type": "verb", "meaning_vi": "Xuất hiện, dường như", "sound_bridge": "Ơ kìa bia xuất hiện trên bàn tiệc kìa.", "definition_en": "come into sight; become visible", "example_en": "A rainbow appeared in the sky.", "example_vi": "Cầu vồng xuất hiện trên bầu trời.", "page_number": 34},
      {"word_number": 69, "word": "Applause", "phonetic": "/əˈplɑːz/", "word_type": "noun", "meaning_vi": "Tràng pháo tay", "sound_bridge": "Ơ phờ lo lắng nhưng vẫn nhận được tràng pháo tay nồng nhiệt.", "definition_en": "approval or praise expressed by clapping", "example_en": "Give a big round of applause!", "example_vi": "Hãy cho một tràng pháo tay thật lớn!", "page_number": 34},
      {"word_number": 70, "word": "Appointment", "phonetic": "/əˈpɔɪnt.mənt/", "word_type": "noun", "meaning_vi": "Cuộc hẹn", "sound_bridge": "Ơ point điểm danh đúng giờ cuộc hẹn nhé.", "definition_en": "an arrangement to meet someone at a particular time and place", "example_en": "I have a dentist appointment today.", "example_vi": "Hôm nay tôi có một cuộc hẹn với nha sĩ.", "page_number": 35},
      {"word_number": 71, "word": "Borrow", "phonetic": "/ˈbɑːr.oʊ/", "word_type": "verb", "meaning_vi": "Mượn, vay mượn", "sound_bridge": "Bò rầu rĩ vì không ai cho mượn tiền cỏ.", "definition_en": "take and use (something that belongs to someone else) with the intention of returning it", "example_en": "Can I borrow your pen?", "example_vi": "Tôi có thể mượn bút của bạn được không?", "page_number": 35},
      {"word_number": 72, "word": "Bother", "phonetic": "/ˈbɑː.ðɚ/", "word_type": "verb", "meaning_vi": "Làm phiền, bận tâm", "sound_bridge": "Bơ thối làm phiền cả căn bếp thơm tho.", "definition_en": "take the trouble to do something / annoy someone", "example_en": "Sorry to bother you.", "example_vi": "Xin lỗi vì đã làm phiền bạn.", "page_number": 35},
      {"word_number": 73, "word": "Claim", "phonetic": "/kleɪm/", "word_type": "verb", "meaning_vi": "Tuyên bố, đòi quyền lợi", "sound_bridge": "Cười lỏm lẻm khi tuyên bố mình thắng cuộc.", "definition_en": "state or assert that something is the case", "example_en": "He claimed he was innocent.", "example_vi": "Anh ta tuyên bố mình vô tội.", "page_number": 35},
      {"word_number": 74, "word": "Client", "phonetic": "/ˈklaɪ.ənt/", "word_type": "noun", "meaning_vi": "Khách hàng", "sound_bridge": "Cái lại ồn ào trước mặt khách hàng VIP rồi.", "definition_en": "a person or organization using the services of a lawyer or other professional person", "example_en": "We must treat every client with respect.", "example_vi": "Chúng ta phải tôn trọng mọi khách hàng.", "page_number": 35},
      {"word_number": 75, "word": "Conversation", "phonetic": "/ˌkɑːn.vɚˈseɪ.ʃən/", "word_type": "noun", "meaning_vi": "Cuộc trò chuyện", "sound_bridge": "Con vợ sợ sệt khi bắt đầu cuộc trò chuyện với mẹ chồng.", "definition_en": "a talk, especially an informal one, between two or more people", "example_en": "We had a long conversation.", "example_vi": "Chúng tôi đã có một cuộc trò chuyện dài.", "page_number": 36},
      {"word_number": 76, "word": "Deny", "phonetic": "/dɪˈnaɪ/", "word_type": "verb", "meaning_vi": "Phủ nhận, từ chối", "sound_bridge": "Đi nài nỉ xin xỏ nhưng vẫn bị phủ nhận.", "definition_en": "state that one refuses to admit the truth or existence of", "example_en": "She denied all allegations.", "example_vi": "Cô ấy phủ nhận mọi cáo buộc.", "page_number": 36},
      {"word_number": 77, "word": "Depress", "phonetic": "/dɪˈpres/", "word_type": "verb", "meaning_vi": "Làm chán nản, thất vọng", "sound_bridge": "Đi phơi rơm mà mưa làm cả nhà chán nản.", "definition_en": "make (someone) feel utterly dispirited or dejected", "example_en": "Rainy weather depresses me.", "example_vi": "Thời tiết mưa gió làm tôi thấy chán nản.", "page_number": 36},
      {"word_number": 78, "word": "Diary", "phonetic": "/ˈdaɪə.ri/", "word_type": "noun", "meaning_vi": "Nhật ký", "sound_bridge": "Đáy rương là nơi cất giữ cuốn nhật ký bí mật.", "definition_en": "a book in which one keeps a daily record of events and experiences", "example_en": "She writes in her diary every night.", "example_vi": "Cô ấy viết nhật ký mỗi tối.", "page_number": 36},
      {"word_number": 79, "word": "Forget", "phonetic": "/fɚˈɡet/", "word_type": "verb", "meaning_vi": "Quên", "sound_bridge": "Phở ghét người nấu vì quên cho hành.", "definition_en": "fail to remember", "example_en": "Don't forget your keys!", "example_vi": "Đừng quên chìa khóa nhé!", "page_number": 36},
      {"word_number": 80, "word": "Invite", "phonetic": "/ɪnˈvaɪt/", "word_type": "verb", "meaning_vi": "Mời", "sound_bridge": "In vài tờ thiệp để mời bạn bè dự tiệc.", "definition_en": "make a polite, formal, or friendly request to (someone) to go somewhere", "example_en": "They invited us to dinner.", "example_vi": "Họ đã mời chúng tôi đến ăn tối.", "page_number": 37},
      {"word_number": 81, "word": "Later", "phonetic": "/ˈleɪ.t̬ɚ/", "word_type": "adverb", "meaning_vi": "Sau đó, lát nữa", "sound_bridge": "Lấy tớ sau này nhé lát nữa hãng tính tiếp.", "definition_en": "at a time in the near future; afterwards", "example_en": "See you later!", "example_vi": "Hẹn gặp lại bạn sau!", "page_number": 37},
      {"word_number": 82, "word": "Matter", "phonetic": "/ˈmæt̬.ɚ/", "word_type": "noun", "meaning_vi": "Vấn đề, chuyện quan trọng", "sound_bridge": "Mát tay chữa khỏi vấn đề nan y này.", "definition_en": "a subject or situation under consideration", "example_en": "It doesn't matter at all.", "example_vi": "Chuyện đó chẳng thành vấn đề gì cả.", "page_number": 37},
      {"word_number": 83, "word": "Obtain", "phonetic": "/əbˈteɪn/", "word_type": "verb", "meaning_vi": "Đạt được, giành được", "sound_bridge": "Ơ tên trộm đã đạt được mục đích lấy cắp báu vật.", "definition_en": "get, acquire, or secure (something)", "example_en": "You need to obtain a permit.", "example_vi": "Bạn cần phải xin được giấy phép.", "page_number": 37},
      {"word_number": 84, "word": "Possess", "phonetic": "/pəˈzes/", "word_type": "verb", "meaning_vi": "Sở hữu", "sound_bridge": "Bơ rét run vì sở hữu viên ngọc quý giá.", "definition_en": "have as belonging to one; own", "example_en": "He possesses great skills.", "example_vi": "Anh ấy sở hữu những kỹ năng tuyệt vời.", "page_number": 37},
      {"word_number": 85, "word": "Purpose", "phonetic": "/ˈpɝː.pəs/", "word_type": "noun", "meaning_vi": "Mục đích", "sound_bridge": "Bơ phờ bớt đi khi tìm thấy mục đích sống.", "definition_en": "the reason for which something is done or created", "example_en": "What is the purpose of this meeting?", "example_vi": "Mục đích của cuộc họp này là gì?", "page_number": 38},
      {"word_number": 86, "word": "Remember", "phonetic": "/rɪˈmem.bɚ/", "word_type": "verb", "meaning_vi": "Nhớ, ghi nhớ", "sound_bridge": "Ri mềm lòng khi nhớ lại kỷ niệm xưa.", "definition_en": "have in or be able to bring to one's mind an awareness of (someone or something)", "example_en": "I remember meeting you last year.", "example_vi": "Tôi nhớ đã gặp bạn vào năm ngoái.", "page_number": 38},
      {"word_number": 87, "word": "Remind", "phonetic": "/rɪˈmaɪnd/", "word_type": "verb", "meaning_vi": "Nhắc nhở", "sound_bridge": "Ri mai nhớ nhắc nhở sếp gửi báo cáo nhé.", "definition_en": "cause (someone) to remember someone or something", "example_en": "Please remind me to call him.", "example_vi": "Làm ơn nhắc tôi gọi cho anh ấy nhé.", "page_number": 38},
      {"word_number": 88, "word": "Rumor", "phonetic": "/ˈruː.mɚ/", "word_type": "noun", "meaning_vi": "Tin đồn", "sound_bridge": "Rủ mơ mộng nghe những tin đồn thất thiệt.", "definition_en": "a currently circulating story or report of uncertain or doubtful truth", "example_en": "Is it true or just a rumor?", "example_vi": "Đó là sự thật hay chỉ là tin đồn?", "page_number": 38},
      {"word_number": 89, "word": "Several", "phonetic": "/ˈsev.ɚ.əl/", "word_type": "adjective", "meaning_vi": "Một vài, một số", "sound_bridge": "Sợ vỡ lọ hoa nên chỉ mang vài cành.", "definition_en": "more than two but not many", "example_en": "I have several questions for you.", "example_vi": "Tôi có một vài câu hỏi cho bạn.", "page_number": 38},
      {"word_number": 90, "word": "Speech", "phonetic": "/spiːtʃ/", "word_type": "noun", "meaning_vi": "Bài phát biểu", "sound_bridge": "Sợ tí sặc nước khi đang đọc bài phát biểu.", "definition_en": "a formal address or discourse delivered to an audience", "example_en": "He gave an inspiring speech.", "example_vi": "Anh ấy đã có một bài phát biểu đầy cảm hứng.", "page_number": 39},
      {"word_number": 91, "word": "Symbol", "phonetic": "/ˈsɪm.bəl/", "word_type": "noun", "meaning_vi": "Biểu tượng", "sound_bridge": "Sim bồ tặng là biểu tượng tình yêu đôi ta.", "definition_en": "a thing that represents or stands for something else", "example_en": "The dove is a symbol of peace.", "example_vi": "Chim bồ câu là biểu tượng của hòa bình.", "page_number": 39},
      {"word_number": 92, "word": "Therefore", "phonetic": "/ˈðer.fɔːr/", "word_type": "adverb", "meaning_vi": "Do đó, vì vậy", "sound_bridge": "Đỡ phở nóng nên do đó không bị bỏng tay.", "definition_en": "for that reason; consequently", "example_en": "He was ill and therefore could not come.", "example_vi": "Anh ấy bị ốm vì vậy không thể đến.", "page_number": 39},
      {"word_number": 93, "word": "Translate", "phonetic": "/trænsˈleɪt/", "word_type": "verb", "meaning_vi": "Dịch, phiên dịch", "sound_bridge": "Tràn lên lầu để dịch bài báo nước ngoài.", "definition_en": "express the sense of (words or text) in another language", "example_en": "Can you translate this sentence for me?", "example_vi": "Bạn có thể dịch câu này giúp tôi không?", "page_number": 39},
      {"word_number": 94, "word": "Underline", "phonetic": "/ˌʌn.dɚˈlaɪn/", "word_type": "verb", "meaning_vi": "Gạch chân, nhấn mạnh", "sound_bridge": "Ăn đòn lại nữa nếu không gạch chân từ khóa quan trọng.", "definition_en": "draw a line under (a word or phrase) to give emphasis", "example_en": "Underline the key words in each sentence.", "example_vi": "Hãy gạch chân các từ khóa trong mỗi câu.", "page_number": 39}
    ]
  },

  # UNIT 4: Communication 4 (30 từ, trang 44-49)
  {
    "unit": 4, "unit_title": "Communication 4", "category": "Communication",
    "words": [
      {"word_number": 95, "word": "Coincide", "phonetic": "/ˌkoʊ.ɪnˈsaɪd/", "word_type": "verb", "meaning_vi": "Trùng hợp", "sound_bridge": "Cố in sai để trùng hợp với bản gốc làm sao được.", "definition_en": "occur at or during the same time", "example_en": "Our birthdays coincide.", "example_vi": "Sinh nhật của chúng tôi trùng ngày nhau.", "page_number": 44},
      {"word_number": 96, "word": "Commit", "phonetic": "/kəˈmɪt/", "word_type": "verb", "meaning_vi": "Cam kết, tận tụy", "sound_bridge": "Có mít ngon cam kết chia đều cho cả nhà.", "definition_en": "pledge or bind (a person or an organization) to a certain course", "example_en": "We commit to providing high quality service.", "example_vi": "Chúng tôi cam kết cung cấp dịch vụ chất lượng cao.", "page_number": 44},
      {"word_number": 97, "word": "Conform", "phonetic": "/kənˈfɔːrm/", "word_type": "verb", "meaning_vi": "Tuân thủ, thích ứng", "sound_bridge": "Còn phom dáng chuẩn thì phải tuân thủ quy tắc giữ gìn.", "definition_en": "comply with rules, standards, or laws", "example_en": "All products must conform to safety regulations.", "example_vi": "Tất cả sản phẩm phải tuân thủ quy định an toàn.", "page_number": 44},
      {"word_number": 98, "word": "Confront", "phonetic": "/kənˈfrʌnt/", "word_type": "verb", "meaning_vi": "Đối đầu, đối mặt", "sound_bridge": "Còn phân vân chưa dám đối mặt với sự thật.", "definition_en": "meet (someone) face to face with hostile intent", "example_en": "He confronted the intruder bravely.", "example_vi": "Anh ấy dũng cảm đối mặt với kẻ đột nhập.", "page_number": 44},
      {"word_number": 99, "word": "Confuse", "phonetic": "/kənˈfjuːz/", "word_type": "verb", "meaning_vi": "Làm bối rối, nhầm lẫn", "sound_bridge": "Cần phao cứu sinh làm bối rối cả hồ bơi.", "definition_en": "cause (someone) to become bewildered or perplexed", "example_en": "Don't confuse me with too many details!", "example_vi": "Đừng làm tôi bối rối với quá nhiều chi tiết!", "page_number": 44},
      {"word_number": 100, "word": "Congratulate", "phonetic": "/kənˈɡrætʃ.ə.leɪt/", "word_type": "verb", "meaning_vi": "Chúc mừng", "sound_bridge": "Cắn quả ớt cay xè nhưng vẫn chúc mừng bạn tốt nghiệp.", "definition_en": "express praise for an achievement or good fortune", "example_en": "I want to congratulate you on your success.", "example_vi": "Tôi muốn chúc mừng bạn vì thành công này.", "page_number": 45},
      {"word_number": 101, "word": "Congress", "phonetic": "/ˈkɑːŋ.ɡrəs/", "word_type": "noun", "meaning_vi": "Quốc hội", "sound_bridge": "Con ghét sự tranh luận nảy lửa trong quốc hội.", "definition_en": "a national legislative body", "example_en": "Congress passed the new bill yesterday.", "example_vi": "Quốc hội đã thông qua dự luật mới hôm qua.", "page_number": 45},
      {"word_number": 102, "word": "Consequence", "phonetic": "/ˈkɑːn.sə.kwəns/", "word_type": "noun", "meaning_vi": "Hậu quả, hệ quả", "sound_bridge": "Con sợ quen ăn vặt sẽ để lại hậu quả béo phì.", "definition_en": "a result or effect of an action or condition", "example_en": "You must face the consequences of your action.", "example_vi": "Bạn phải đối mặt với hậu quả do hành động của mình.", "page_number": 45},
      {"word_number": 103, "word": "Consider", "phonetic": "/kənˈsɪd.ɚ/", "word_type": "verb", "meaning_vi": "Cân nhắc, xem xét", "sound_bridge": "Cơn si mê làm bạn quên cân nhắc điều kiện thực tế.", "definition_en": "think carefully about (something), typically before making a decision", "example_en": "Please consider our proposal carefully.", "example_vi": "Làm ơn xem xét kỹ đề xuất của chúng tôi.", "page_number": 45},
      {"word_number": 104, "word": "Deceive", "phonetic": "/dɪˈsiːv/", "word_type": "verb", "meaning_vi": "Lừa dối, lừa gạt", "sound_bridge": "Đi ship hàng mà bị lừa dối nhận cọc ảo.", "definition_en": "cause (someone) to believe something that is not true", "example_en": "He deceived his friends for money.", "example_vi": "Anh ta đã lừa dối bạn bè để lấy tiền.", "page_number": 45},
      {"word_number": 105, "word": "Dialogue", "phonetic": "/ˈdaɪ.ə.lɑːɡ/", "word_type": "noun", "meaning_vi": "Hội thoại, đối thoại", "sound_bridge": "Đái ở góc tường làm gián đoạn cuộc đối thoại quan trọng.", "definition_en": "conversation between two or more people as a feature of a book, play, or movie", "example_en": "Practice the dialogue in pairs.", "example_vi": "Luyện tập bài hội thoại theo cặp.", "page_number": 46},
      {"word_number": 106, "word": "Discrepancy", "phonetic": "/dɪˈskrep.ən.si/", "word_type": "noun", "meaning_vi": "Sự khác biệt, không nhất quán", "sound_bridge": "Đi sợ kẹp tay vì sự sai lệch của kích thước cửa.", "definition_en": "a lack of compatibility or similarity between two or more facts", "example_en": "There is a discrepancy in the budget report.", "example_vi": "Có sự sai lệch trong báo cáo ngân sách.", "page_number": 46},
      {"word_number": 107, "word": "Envelope", "phonetic": "/ˈen.və.loʊp/", "word_type": "noun", "meaning_vi": "Phong bì, phong thư", "sound_bridge": "Em về lợp ngói cất phong bì tiền mừng cưới.", "definition_en": "a flat paper container for a letter", "example_en": "Put the letter in the envelope.", "example_vi": "Hãy bỏ lá thư vào trong phong bì.", "page_number": 46},
      {"word_number": 108, "word": "Especially", "phonetic": "/ɪˈspeʃ.əl.i/", "word_type": "adverb", "meaning_vi": "Đặc biệt là", "sound_bridge": "Em sợ bé xỉu vì trời quá nóng đặc biệt là buổi trưa.", "definition_en": "used to single out one person, thing, or situation over all others", "example_en": "I love fruits, especially mangos.", "example_vi": "Tôi thích trái cây, đặc biệt là xoài.", "page_number": 46},
      {"word_number": 109, "word": "Hyphen", "phonetic": "/ˈhaɪ.fən/", "word_type": "noun", "meaning_vi": "Dấu gạch nối", "sound_bridge": "Hai phần bánh được nối bằng dấu gạch nối.", "definition_en": "the sign (-) used to join words to indicate that they have a combined meaning", "example_en": "Use a hyphen between compound words.", "example_vi": "Hãy dùng dấu gạch nối giữa các từ ghép.", "page_number": 46},
      {"word_number": 110, "word": "Impress", "phonetic": "/ɪmˈpres/", "word_type": "verb", "meaning_vi": "Gây ấn tượng", "sound_bridge": "In phao rớt nước vẫn gây ấn tượng vì học giỏi.", "definition_en": "make (someone) feel admiration and respect", "example_en": "His performance impressed everyone.", "example_vi": "Màn trình diễn của anh ấy đã gây ấn tượng với mọi người.", "page_number": 47},
      {"word_number": 111, "word": "Indicate", "phonetic": "/ˈɪn.də.keɪt/", "word_type": "verb", "meaning_vi": "Chỉ ra, biểu thị", "sound_bridge": "In đĩa kết quả để chỉ ra lỗi sai của thí sinh.", "definition_en": "point out; show", "example_en": "The red light indicates danger.", "example_vi": "Đèn đỏ biểu thị sự nguy hiểm.", "page_number": 47},
      {"word_number": 112, "word": "Legend", "phonetic": "/ˈledʒ.ənd/", "word_type": "noun", "meaning_vi": "Huyền thoại, truyền thuyết", "sound_bridge": "Lệ giàn giụa khi nghe kể về truyền thuyết người anh hùng.", "definition_en": "a traditional story sometimes popularly regarded as historical but unauthenticated", "example_en": "He is a living legend in music.", "example_vi": "Anh ấy là một huyền thoại sống trong âm nhạc.", "page_number": 47},
      {"word_number": 113, "word": "Moment", "phonetic": "/ˈmoʊ.mənt/", "word_type": "noun", "meaning_vi": "Khoảnh khắc, chốc lát", "sound_bridge": "Mở mắt ra là khoảnh khắc bình minh tuyệt đẹp.", "definition_en": "a very brief period of time", "example_en": "Wait for me for a moment!", "example_vi": "Chờ tôi một khoảnh khắc nhé!", "page_number": 47},
      {"word_number": 114, "word": "Recall", "phonetic": "/rɪˈkɑːl/", "word_type": "verb", "meaning_vi": "Nhớ lại, thu hồi", "sound_bridge": "Ri cào cấu khi cố nhớ lại mật khẩu két sắt.", "definition_en": "bring (a fact, event, or situation) back into one's mind", "example_en": "I can't recall his exact words.", "example_vi": "Tôi không thể nhớ lại chính xác lời anh ấy nói.", "page_number": 47},
      {"word_number": 115, "word": "Recommend", "phonetic": "/ˌrek.əˈmend/", "word_type": "verb", "meaning_vi": "Khuyên, giới thiệu", "sound_bridge": "Rét cắn môi vẫn nhiệt tình giới thiệu quán ăn ngon.", "definition_en": "put forward (someone or something) with approval as being suitable for a purpose", "example_en": "I highly recommend this book.", "example_vi": "Tôi rất khuyên bạn nên đọc cuốn sách này.", "page_number": 48},
      {"word_number": 116, "word": "Refer", "phonetic": "/rɪˈfɝː/", "word_type": "verb", "meaning_vi": "Tham khảo, ám chỉ", "sound_bridge": "Ri phởn phơ khi tham khảo tài liệu trúng đề.", "definition_en": "mention or allude to", "example_en": "Please refer to page 10 for details.", "example_vi": "Vui lòng tham khảo trang 10 để biết thêm chi tiết.", "page_number": 48},
      {"word_number": 117, "word": "Refuse", "phonetic": "/rɪˈfjuːz/", "word_type": "verb", "meaning_vi": "Từ chối", "sound_bridge": "Ri phì cười từ chối lời mời đi bar thâu đêm.", "definition_en": "indicate or show that one is not willing to do something", "example_en": "He refused to answer my question.", "example_vi": "Anh ấy từ chối trả lời câu hỏi của tôi.", "page_number": 48},
      {"word_number": 118, "word": "Relevant", "phonetic": "/ˈrel.ə.vənt/", "word_type": "adjective", "meaning_vi": "Liên quan, thích hợp", "sound_bridge": "Rẽ lối vào nơi liên quan đến dự án mới.", "definition_en": "closely connected or appropriate to what is being done or considered", "example_en": "Provide all relevant documents.", "example_vi": "Cung cấp tất cả các tài liệu có liên quan.", "page_number": 48},
      {"word_number": 119, "word": "Repel", "phonetic": "/rɪˈpel/", "word_type": "verb", "meaning_vi": "Đẩy lùi, xua đuổi", "sound_bridge": "Ri béo đẩy lùi cơn buồn ngủ bằng cốc cà phê đen.", "definition_en": "drive or force (an attack or attacker) back or away", "example_en": "This spray repels mosquitoes effectively.", "example_vi": "Bình xịt này xua đuổi muỗi rất hiệu quả.", "page_number": 48},
      {"word_number": 120, "word": "Represent", "phonetic": "/ˌrep.rɪˈzent/", "word_type": "verb", "meaning_vi": "Đại diện", "sound_bridge": "Rét run người nhưng vẫn đứng ra đại diện cho cả đoàn.", "definition_en": "be entitled or appointed to act or speak for (someone)", "example_en": "She represents our company at the summit.", "example_vi": "Cô ấy đại diện công ty chúng tôi tại hội nghị thượng đỉnh.", "page_number": 49},
      {"word_number": 121, "word": "Signature", "phonetic": "/ˈsɪɡ.nə.tʃɚ/", "word_type": "noun", "meaning_vi": "Chữ ký", "sound_bridge": "Xin nợ chưa trả thì chưa được đóng chữ ký xác nhận.", "definition_en": "a person's name written in a distinctive way as a form of identification", "example_en": "Put your signature at the bottom of the page.", "example_vi": "Hãy ký tên ở cuối trang.", "page_number": 49},
      {"word_number": 122, "word": "Statement", "phonetic": "/ˈsteɪt.mənt/", "word_type": "noun", "meaning_vi": "Lời tuyên bố, bản sao kê", "sound_bridge": "Sợ tết mệt mỏi nghe bản sao kê tài chính cuối năm.", "definition_en": "a definite or clear expression of something in speech or writing", "example_en": "The minister issued an official statement.", "example_vi": "Bộ trưởng đã đưa ra một tuyên bố chính thức.", "page_number": 49},
      {"word_number": 123, "word": "Strain", "phonetic": "/streɪn/", "word_type": "noun", "meaning_vi": "Sự căng thẳng, áp lực", "sound_bridge": "Sợ trượt ray tàu tạo áp lực căng thẳng cho hành khách.", "definition_en": "a state of tension or exhaustion resulting from severe effort", "example_en": "The strain of working late affected his health.", "example_vi": "Áp lực làm việc muộn ảnh hưởng xấu đến sức khỏe anh ấy.", "page_number": 49},
      {"word_number": 124, "word": "Sympathy", "phonetic": "/ˈsɪm.pə.θi/", "word_type": "noun", "meaning_vi": "Sự đồng cảm, thương cảm", "sound_bridge": "Sim bà thi đỗ nhận được nhiều sự chia sẻ và đồng cảm.", "definition_en": "feelings of pity and sorrow for someone else's misfortune", "example_en": "I have deep sympathy for the victims.", "example_vi": "Tôi có sự đồng cảm sâu sắc với các nạn nhân.", "page_number": 49}
    ]
  }
]

# Nạp vào file JSON
all_vocab = []
for u in units:
  for w in u["words"]:
    w["unit"] = u["unit"]
    w["unit_title"] = u["unit_title"]
    w["category"] = u["category"]
    w["status"] = "new"
    all_vocab.append(w)

with open('backend/data/hacknao_vocab.json', 'w', encoding='utf-8') as f:
  json.dump(all_vocab, f, ensure_ascii=False, indent=2)

print(f"Hoàn tất nạp {len(all_vocab)} từ vựng từ Unit 1 đến Unit 4 vào JSON.")
