import json
import os

# Toàn bộ từ vựng Units 5, 6, 7, 8, 9, 10 chuẩn từ sách Hack Não 1500

units_5_to_10 = [
  # UNIT 5: Equipment and Experiment (29 từ, trang 53-58)
  {
    "unit": 5, "unit_title": "Equipment and Experiment", "category": "Equipment & Science",
    "words": [
      {"word_number": 125, "word": "Durable", "phonetic": "/ˈdʊr.ə.bəl/", "word_type": "adjective", "meaning_vi": "Bền bỉ, lâu bền", "sound_bridge": "Đưa ra bờ biển kiểm tra độ bền bỉ của áo phao.", "definition_en": "able to withstand wear, pressure, or damage", "example_en": "These boots are durable and waterproof.", "example_vi": "Đôi bốt này rất bền và chống nước.", "page_number": 53},
      {"word_number": 126, "word": "Edition", "phonetic": "/ɪˈdɪʃ.ən/", "word_type": "noun", "meaning_vi": "Phiên bản, lần xuất bản", "sound_bridge": "Em đi săn phiên bản sách đặc biệt có chữ ký tác giả.", "definition_en": "a particular form or version of a published text", "example_en": "This is the third edition of the dictionary.", "example_vi": "Đây là lần xuất bản thứ ba của cuốn từ điển.", "page_number": 53},
      {"word_number": 127, "word": "Element", "phonetic": "/ˈel.ə.mənt/", "word_type": "noun", "meaning_vi": "Yếu tố, nguyên tố", "sound_bridge": "Em lại mượn bảng tuần hoàn nguyên tố hóa học.", "definition_en": "an essential or characteristic part of something abstract", "example_en": "Trust is a key element of any relationship.", "example_vi": "Sự tin tưởng là yếu tố then chốt trong mọi mối quan hệ.", "page_number": 53},
      {"word_number": 128, "word": "Elevator", "phonetic": "/ˈel.ə.veɪ.t̬ɚ/", "word_type": "noun", "meaning_vi": "Thang máy", "sound_bridge": "Em lo vé thang máy bị kẹt giữa chừng.", "definition_en": "a platform or compartment housed in a shaft for raising and lowering people", "example_en": "Take the elevator to the 10th floor.", "example_vi": "Hãy đi thang máy lên tầng 10.", "page_number": 53},
      {"word_number": 129, "word": "Equipment", "phonetic": "/ɪˈkwɪp.mənt/", "word_type": "noun", "meaning_vi": "Thiết bị, dụng cụ", "sound_bridge": "Ê kíp mình cần chuẩn bị thiết bị quay phim chu đáo.", "definition_en": "the necessary items for a particular purpose", "example_en": "The laboratory has state-of-the-art equipment.", "example_vi": "Phòng thí nghiệm có trang thiết bị tối tân.", "page_number": 54},
      {"word_number": 130, "word": "Experiment", "phonetic": "/ɪkˈsper.ə.mənt/", "word_type": "noun", "meaning_vi": "Cuộc thí nghiệm", "sound_bridge": "Ếch sợ mệt khi tham gia cuộc thí nghiệm sinh học.", "definition_en": "a scientific procedure undertaken to make a discovery", "example_en": "The experiment was a complete success.", "example_vi": "Cuộc thí nghiệm đã thành công tốt đẹp.", "page_number": 54},
      {"word_number": 131, "word": "Former", "phonetic": "/ˈfɔːr.mɚ/", "word_type": "adjective", "meaning_vi": "Trước đây, cựu", "sound_bridge": "Phở mỡ trước đây là món yêu thích của ông cựu chủ tịch.", "definition_en": "having previously been a particular thing", "example_en": "She met her former boss yesterday.", "example_vi": "Hôm qua cô ấy đã gặp lại sếp cũ của mình.", "page_number": 54},
      {"word_number": 132, "word": "Fulfill", "phonetic": "/fʊlˈfɪl/", "word_type": "verb", "meaning_vi": "Hoàn thành, đáp ứng", "sound_bridge": "Phút phiêu lưu giúp anh hoàn thành ước nguyện tuổi trẻ.", "definition_en": "bring to completion or reality", "example_en": "He fulfilled his dream of becoming a pilot.", "example_vi": "Anh ấy đã hoàn thành ước mơ trở thành phi công.", "page_number": 54},
      {"word_number": 133, "word": "Fund", "phonetic": "/fʌnd/", "word_type": "noun", "meaning_vi": "Quỹ, nguồn vốn", "sound_bridge": "Phần đông mọi người đóng góp vào quỹ từ thiện.", "definition_en": "a sum of money saved or made available for a particular purpose", "example_en": "The project ran out of funds.", "example_vi": "Dự án đã hết nguồn quỹ tài trợ.", "page_number": 54},
      {"word_number": 134, "word": "Gain", "phonetic": "/ɡeɪn/", "word_type": "verb", "meaning_vi": "Đạt được, thu được", "sound_bridge": "Gần gũi học hỏi để thu được nhiều kinh nghiệm quý báu.", "definition_en": "obtain or secure (something desired or favorable)", "example_en": "You will gain valuable experience here.", "example_vi": "Bạn sẽ đạt được những kinh nghiệm quý giá ở đây.", "page_number": 54},
      {"word_number": 135, "word": "General", "phonetic": "/ˈdʒen.ər.əl/", "word_type": "adjective", "meaning_vi": "Tổng quát, chung", "sound_bridge": "Giận hờn vu vơ làm ảnh hưởng không khí chung của cả phòng.", "definition_en": "affecting or concerning all or most people, places, or things", "example_en": "In general, the results are positive.", "example_vi": "Nhìn chung, kết quả rất tích cực.", "page_number": 55},
      {"word_number": 136, "word": "Generate", "phonetic": "/ˈdʒen.ə.reɪt/", "word_type": "verb", "meaning_vi": "Tạo ra, phát ra", "sound_bridge": "Chèn ép rớt nước mắt nhưng vẫn tạo ra năng lượng tích cực.", "definition_en": "cause (something, especially an emotion or situation) to arise or come about", "example_en": "Windmills generate clean electricity.", "example_vi": "Cối xay gió tạo ra điện năng sạch.", "page_number": 55},
      {"word_number": 137, "word": "Hammer", "phonetic": "/ˈhæm.ɚ/", "word_type": "noun", "meaning_vi": "Cái búa", "sound_bridge": "Hàm răng đau nhức như bị búa gõ vào.", "definition_en": "a tool with a heavy metal head mounted at right angles at the end of a handle", "example_en": "Use a hammer to hit the nail.", "example_vi": "Hãy dùng búa để đóng chiếc đinh.", "page_number": 55},
      {"word_number": 138, "word": "Leak", "phonetic": "/liːk/", "word_type": "verb", "meaning_vi": "Rò rỉ", "sound_bridge": "Ly kem tan chảy rò rỉ khắp mặt bàn.", "definition_en": "accidentally lose or admit contents, especially liquid or gas", "example_en": "The pipe is leaking water.", "example_vi": "Đường ống đang bị rò rỉ nước.", "page_number": 55},
      {"word_number": 139, "word": "Perspective", "phonetic": "/pɚˈspek.tɪv/", "word_type": "noun", "meaning_vi": "Góc nhìn, quan điểm", "sound_bridge": "Bơ sợ bết tóc khi thay đổi góc nhìn dưới ánh đèn.", "definition_en": "a particular attitude toward or way of regarding something", "example_en": "Try to look at it from another perspective.", "example_vi": "Hãy thử nhìn nhận từ một góc nhìn khác.", "page_number": 55},
      {"word_number": 140, "word": "Presume", "phonetic": "/prɪˈzuːm/", "word_type": "verb", "meaning_vi": "Cho là, đoán chừng", "sound_bridge": "Phi rủ mừng sinh nhật vì cho là mọi người đã chuẩn bị xong.", "definition_en": "suppose that something is the case on the basis of probability", "example_en": "I presume you already know the answer.", "example_vi": "Tôi đoán chừng bạn đã biết câu trả lời rồi.", "page_number": 56},
      {"word_number": 141, "word": "Proof", "phonetic": "/pruːf/", "word_type": "noun", "meaning_vi": "Bằng chứng", "sound_bridge": "Phù phép biến mất bằng chứng tại hiện trường.", "definition_en": "evidence or argument establishing or helping to establish a fact or the truth of a statement", "example_en": "Do you have any proof of payment?", "example_vi": "Bạn có bằng chứng thanh toán nào không?", "page_number": 56},
      {"word_number": 142, "word": "Proofreader", "phonetic": "/ˈpruːfˌriː.dɚ/", "word_type": "noun", "meaning_vi": "Người sửa bản in thử", "sound_bridge": "Phù phép rủ người sửa bản in đọc kỹ từng câu chữ.", "definition_en": "a person whose job is to read and correct errors in a printed text", "example_en": "The proofreader found three typos in the article.", "example_vi": "Người sửa bản in đã tìm ra ba lỗi chính tả trong bài viết.", "page_number": 56},
      {"word_number": 143, "word": "Pure", "phonetic": "/pjʊr/", "word_type": "adjective", "meaning_vi": "Nguyên chất, tinh khiết", "sound_bridge": "Phi tiêu rơi xuống hồ nước tinh khiết trong vắt.", "definition_en": "not mixed or adulterated with any other substance or material", "example_en": "This bottle contains pure mineral water.", "example_vi": "Chai này chứa nước khoáng tinh khiết.", "page_number": 56},
      {"word_number": 144, "word": "Range", "phonetic": "/reɪndʒ/", "word_type": "noun", "meaning_vi": "Phạm vi, dãy", "sound_bridge": "Rên rỉ vì phạm vi bài kiểm tra quá rộng.", "definition_en": "the area of variation between upper and lower limits on a particular scale", "example_en": "We offer a wide range of products.", "example_vi": "Chúng tôi cung cấp một phạm vi đa dạng các sản phẩm.", "page_number": 56},
      {"word_number": 145, "word": "Ray", "phonetic": "/reɪ/", "word_type": "noun", "meaning_vi": "Tia sáng", "sound_bridge": "Rơi lệ khi đón tia sáng bình minh đầu tiên.", "definition_en": "each of the lines in which light (and heat) may seem to stream from the sun", "example_en": "A ray of sunlight came through the window.", "example_vi": "Một tia nắng chiếu xuyên qua cửa sổ.", "page_number": 57},
      {"word_number": 146, "word": "Section", "phonetic": "/ˈsek.ʃən/", "word_type": "noun", "meaning_vi": "Phần, mục", "sound_bridge": "Sách sờn góc ở mục lục trang đầu.", "definition_en": "any of the more or less distinct parts into which something is or may be divided", "example_en": "Read the next section of the chapter.", "example_vi": "Hãy đọc phần tiếp theo của chương này.", "page_number": 57},
      {"word_number": 147, "word": "Sector", "phonetic": "/ˈsek.tɚ/", "word_type": "noun", "meaning_vi": "Khu vực, ngành nghề", "sound_bridge": "Sợ cọp tới quấy phá khu vực rừng phòng hộ.", "definition_en": "an area or portion that is distinct from others", "example_en": "The technology sector is growing rapidly.", "example_vi": "Ngành công nghệ đang phát triển nhanh chóng.", "page_number": 57},
      {"word_number": 148, "word": "Significant", "phonetic": "/sɪɡˈnɪf.ə.kənt/", "word_type": "adjective", "meaning_vi": "Quan trọng, có ý nghĩa", "sound_bridge": "Xin nợ phiền phức nhưng mang ý nghĩa quan trọng với tôi.", "definition_en": "sufficiently great or important to be worthy of attention; noteworthy", "example_en": "There is a significant improvement in your scores.", "example_vi": "Có sự tiến bộ rõ rệt và đáng kể trong điểm số của bạn.", "page_number": 57},
      {"word_number": 149, "word": "Skeleton", "phonetic": "/ˈskel.ə.t̬ən/", "word_type": "noun", "meaning_vi": "Bộ xương, khung", "sound_bridge": "Sợ kẻ lén trộm bộ xương hóa thạch trong viện bảo tàng.", "definition_en": "an internal or external framework of bone, cartilage, or other rigid material", "example_en": "The museum has a dinosaur skeleton.", "example_vi": "Viện bảo tàng có một bộ xương khủng long.", "page_number": 57},
      {"word_number": 150, "word": "Sleeve", "phonetic": "/sliːv/", "word_type": "noun", "meaning_vi": "Tay áo", "sound_bridge": "Sợ lí nhí làm bẩn tay áo sơ mi trắng.", "definition_en": "the part of a garment that wholly or partly covers a person's arm", "example_en": "Roll up your sleeves before washing dishes.", "example_vi": "Xắn tay áo lên trước khi rửa bát nhé.", "page_number": 58},
      {"word_number": 151, "word": "Sponsor", "phonetic": "/ˈspɑːn.sɚ/", "word_type": "noun", "meaning_vi": "Nhà tài trợ", "sound_bridge": "Sợ bận rộn nên nhà tài trợ gửi quà từ xa.", "definition_en": "a person or organization that provides funds for an activity or event", "example_en": "Nike is the main sponsor of the event.", "example_vi": "Nike là nhà tài trợ chính của sự kiện này.", "page_number": 58},
      {"word_number": 152, "word": "Stuff", "phonetic": "/stʌf/", "word_type": "noun", "meaning_vi": "Đồ đạc, thứ", "sound_bridge": "Sợ thấp thỏm khi cất đồ đạc quý giá trong tủ.", "definition_en": "matter, material, articles, or activities of a specified or indeterminate kind", "example_en": "Put your stuff on the table.", "example_vi": "Hãy để đồ đạc của bạn lên bàn.", "page_number": 58},
      {"word_number": 153, "word": "Subject to", "phonetic": "/ˈsʌb.dʒekt tuː/", "word_type": "phrase", "meaning_vi": "Tùy thuộc vào", "sound_bridge": "Sắp xếp tới trường tùy thuộc vào kết quả thi.", "definition_en": "only able to happen if something else happens", "example_en": "The flight is subject to weather conditions.", "example_vi": "Chuyến bay tùy thuộc vào điều kiện thời tiết.", "page_number": 58}
    ]
  },

  # UNIT 6: Food & Drink 1 (23 từ, trang 62-67)
  {
    "unit": 6, "unit_title": "Food & Drink 1", "category": "Food & Beverage",
    "words": [
      {"word_number": 154, "word": "Bacon", "phonetic": "/ˈbeɪ.kən/", "word_type": "noun", "meaning_vi": "Thịt xông khói", "sound_bridge": "Bà cắn miếng thịt xông khói giòn rụm trong bữa sáng.", "definition_en": "cured meat from the sides and belly of a pig", "example_en": "I like eggs and bacon for breakfast.", "example_vi": "Tôi thích ăn trứng và thịt xông khói cho bữa sáng.", "page_number": 62},
      {"word_number": 155, "word": "Broccoli", "phonetic": "/ˈbrɑː.kəl.i/", "word_type": "noun", "meaning_vi": "Súp lơ xanh", "sound_bridge": "Bò rầu rĩ vì chỉ được ăn súp lơ xanh luộc.", "definition_en": "a cultivated variety of cabbage with edible flower heads", "example_en": "Broccoli is very rich in vitamin C.", "example_vi": "Súp lơ xanh rất giàu vitamin C.", "page_number": 62},
      {"word_number": 156, "word": "Cabbage", "phonetic": "/ˈkæb.ɪdʒ/", "word_type": "noun", "meaning_vi": "Bắp cải", "sound_bridge": "Cả bầy chuột gặm nhấm bắp cải ngoài vườn.", "definition_en": "a cultivated plant eaten as a vegetable", "example_en": "We made cabbage salad today.", "example_vi": "Hôm nay chúng tôi làm món salad bắp cải.", "page_number": 62},
      {"word_number": 157, "word": "Champagne", "phonetic": "/ʃæmˈpeɪn/", "word_type": "noun", "meaning_vi": "Rượu sâm panh", "sound_bridge": "Sợ bạn phàn nàn nên mở chai rượu sâm panh thượng hạng.", "definition_en": "a white sparkling wine from Champagne, France", "example_en": "They popped a bottle of champagne to celebrate.", "example_vi": "Họ đã bật một chai sâm panh để ăn mừng.", "page_number": 62},
      {"word_number": 158, "word": "Cucumber", "phonetic": "/ˈkjuː.kʌm.bɚ/", "word_type": "noun", "meaning_vi": "Dưa chuột", "sound_bridge": "Cứ cắm cúi ăn dưa chuột giải nhiệt mùa hè.", "definition_en": "a long, green-skinned fruit with watery flesh", "example_en": "Add some cucumber slices to the dish.", "example_vi": "Thêm vài lát dưa chuột vào món ăn nhé.", "page_number": 63},
      {"word_number": 159, "word": "Dessert", "phonetic": "/dɪˈzɝːt/", "word_type": "noun", "meaning_vi": "Món tráng miệng", "sound_bridge": "Đi dạo phố chọn mua món tráng miệng bánh ngọt.", "definition_en": "the sweet course eaten at the end of a meal", "example_en": "What would you like for dessert?", "example_vi": "Bạn muốn dùng món gì cho tráng miệng?", "page_number": 63},
      {"word_number": 160, "word": "Flour", "phonetic": "/flaʊ.ɚ/", "word_type": "noun", "meaning_vi": "Bột mì", "sound_bridge": "Phải lau sạch bột mì vương vãi trên sàn bếp.", "definition_en": "a powder obtained by grinding grain, typically wheat", "example_en": "Mix the flour with two cups of water.", "example_vi": "Trộn bột mì với hai cốc nước.", "page_number": 63},
      {"word_number": 161, "word": "Juice", "phonetic": "/dʒuːs/", "word_type": "noun", "meaning_vi": "Nước ép", "sound_bridge": "Chú uống ly nước ép cam tươi ngon lành.", "definition_en": "the liquid obtained from fruit or vegetables", "example_en": "A glass of orange juice, please.", "example_vi": "Làm ơn cho tôi một ly nước ép cam.", "page_number": 63},
      {"word_number": 162, "word": "Lemonade", "phonetic": "/ˌlem.əˈneɪd/", "word_type": "noun", "meaning_vi": "Nước chanh", "sound_bridge": "Lấy một ly nước chanh mát lạnh giải khát.", "definition_en": "a drink made from lemon juice and water sweetened with sugar", "example_en": "Fresh lemonade is refreshing on hot days.", "example_vi": "Nước chanh tươi rất sảng khoái vào những ngày nóng.", "page_number": 64},
      {"word_number": 163, "word": "Mint", "phonetic": "/mɪnt/", "word_type": "noun", "meaning_vi": "Bạc hà", "sound_bridge": "Mình thích mùi thơm mát của lá bạc hà trong trà.", "definition_en": "an aromatic plant with leaves used for flavoring", "example_en": "Garnish the drink with fresh mint leaves.", "example_vi": "Trang trí thức uống bằng lá bạc hà tươi.", "page_number": 64},
      {"word_number": 164, "word": "Mushroom", "phonetic": "/ˈmʌʃ.rʊm/", "word_type": "noun", "meaning_vi": "Nấm", "sound_bridge": "Mẹ sắm rổ nấm hương về nấu canh súp.", "definition_en": "a fungal growth that typically takes the form of a domed cap on a stalk", "example_en": "I ordered a mushroom pizza.", "example_vi": "Tôi đã gọi một chiếc bánh pizza nấm.", "page_number": 64},
      {"word_number": 165, "word": "Pepper", "phonetic": "/ˈpep.ɚ/", "word_type": "noun", "meaning_vi": "Hạt tiêu, ớt chuông", "sound_bridge": "Bé sợ hạt tiêu cay nồng làm hắt hơi liên tục.", "definition_en": "a pungent hot-tasting powder used as a spice", "example_en": "Add salt and black pepper to taste.", "example_vi": "Thêm muối và tiêu đen cho vừa khẩu vị.", "page_number": 64},
      {"word_number": 166, "word": "Powder", "phonetic": "/ˈpaʊ.dɚ/", "word_type": "noun", "meaning_vi": "Bột", "sound_bridge": "Bao đơ người khi thấy bột ớt đỏ rực trong hũ.", "definition_en": "fine, dry particles produced by the grinding or crushing of a solid substance", "example_en": "Baking powder is needed for the cake.", "example_vi": "Cần có bột nở để làm bánh này.", "page_number": 65},
      {"word_number": 167, "word": "Recipe", "phonetic": "/ˈres.ə.pi/", "word_type": "noun", "meaning_vi": "Công thức nấu ăn", "sound_bridge": "Rẽ sang tiệm mua sách công thức nấu ăn gia truyền.", "definition_en": "a set of instructions for preparing a particular dish", "example_en": "Follow this easy recipe to make pancakes.", "example_vi": "Làm theo công thức dễ dàng này để làm bánh kếp.", "page_number": 65},
      {"word_number": 168, "word": "Sausage", "phonetic": "/ˈsɑː.sɪdʒ/", "word_type": "noun", "meaning_vi": "Xúc xích", "sound_bridge": "Sợ xích xúc xích bị chó cắn mất miếng ngon.", "definition_en": "an item of food in the form of a cylindrical tube of minced meat", "example_en": "Grilled sausage smells wonderful.", "example_vi": "Món xúc xích nướng có mùi thơm tuyệt vời.", "page_number": 65},
      {"word_number": 169, "word": "Shrimp", "phonetic": "/ʃrɪmp/", "word_type": "noun", "meaning_vi": "Tôm", "sound_bridge": "Sợ rim tôm bị cháy khét làm hỏng bữa cơm.", "definition_en": "a small, free-swimming crustacean with an elongated body", "example_en": "Stir-fried shrimp with vegetables is delicious.", "example_vi": "Tôm xào rau củ ăn rất ngon.", "page_number": 65},
      {"word_number": 170, "word": "Sour", "phonetic": "/saʊ.ɚ/", "word_type": "adjective", "meaning_vi": "Chua", "sound_bridge": "Sợ ấu trùng ăn hết chùm me chua trên cành.", "definition_en": "having an acid taste like lemon or vinegar", "example_en": "This green apple is very sour.", "example_vi": "Quả táo xanh này rất chua.", "page_number": 66},
      {"word_number": 171, "word": "Spinach", "phonetic": "/ˈspɪn.ɪtʃ/", "word_type": "noun", "meaning_vi": "Rau chân vịt, cải bó xôi", "sound_bridge": "Sợ bị nịch bụng nên chỉ ăn rau chân vịt luộc.", "definition_en": "an edible flowering plant in the family Amaranthaceae", "example_en": "Popeye loves eating fresh spinach for strength.", "example_vi": "Thủy thủ Popeye thích ăn rau chân vịt tươi để lấy sức mạnh.", "page_number": 66},
      {"word_number": 172, "word": "Squash", "phonetic": "/skwɑːʃ/", "word_type": "noun", "meaning_vi": "Quả bí", "sound_bridge": "Sợ quả bí quá nặng làm gãy giàn leo.", "definition_en": "an edible gourd, the flesh of which may be cooked and eaten as a vegetable", "example_en": "We harvested lots of squash this autumn.", "example_vi": "Chúng tôi đã thu hoạch rất nhiều bí vào mùa thu này.", "page_number": 66},
      {"word_number": 173, "word": "Steak", "phonetic": "/steɪk/", "word_type": "noun", "meaning_vi": "Bít tết", "sound_bridge": "Sợ tếch đi mất đĩa bít tết bò Mỹ thơm lừng.", "definition_en": "high-quality beef taken from the hindquarters of the animal", "example_en": "How would you like your steak cooked?", "example_vi": "Bạn muốn món bít tết được nấu chín như thế nào?", "page_number": 66},
      {"word_number": 174, "word": "Tuna", "phonetic": "/ˈtuː.nə/", "word_type": "noun", "meaning_vi": "Cá ngừ", "sound_bridge": "Tự nâng giỏ cá ngừ đại dương lên thuyền.", "definition_en": "a large and active predatory schooling fish of temperate and tropical seas", "example_en": "I love tuna salad sandwiches.", "example_vi": "Tôi rất thích bánh mì kẹp salad cá ngừ.", "page_number": 67},
      {"word_number": 175, "word": "Vegetarian", "phonetic": "/ˌvedʒ.əˈter.i.ən/", "word_type": "noun", "meaning_vi": "Người ăn chay", "sound_bridge": "Về quê tự tay trồng rau cho người ăn chay thưởng thức.", "definition_en": "a person who does not eat meat or fish", "example_en": "She has been a vegetarian for five years.", "example_vi": "Cô ấy đã là người ăn chay được 5 năm.", "page_number": 67},
      {"word_number": 176, "word": "Vinegar", "phonetic": "/ˈvɪn.ə.ɡɚ/", "word_type": "noun", "meaning_vi": "Giấm", "sound_bridge": "Vì nể gã đầu bếp nên mới nếm thử chén giấm chua.", "definition_en": "a sour-tasting liquid containing acetic acid", "example_en": "Mix olive oil and vinegar for the dressing.", "example_vi": "Trộn dầu ô liu và giấm để làm sốt salad.", "page_number": 67}
    ]
  },

  # UNIT 7: Food & Drink 2 (21 từ, trang 71-75)
  {
    "unit": 7, "unit_title": "Food & Drink 2", "category": "Food & Beverage",
    "words": [
      {"word_number": 177, "word": "Appetite", "phonetic": "/ˈæp.ə.taɪt/", "word_type": "noun", "meaning_vi": "Sự thèm ăn, khẩu vị", "sound_bridge": "Ăn vài trái táo làm tăng khẩu vị thèm ăn.", "definition_en": "a natural desire to satisfy a bodily need, especially for food", "example_en": "Exercise gives you a good appetite.", "example_vi": "Tập thể dục giúp bạn có cảm giác thèm ăn ngon miệng.", "page_number": 71},
      {"word_number": 178, "word": "Barbecue", "phonetic": "/ˈbɑːr.bə.kjuː/", "word_type": "noun", "meaning_vi": "Tiệc nướng ngoài trời", "sound_bridge": "Bà bận kéo lò nướng chuẩn bị tiệc thịt nướng.", "definition_en": "a meal or gathering at which meat, fish, or other food is cooked out of doors", "example_en": "We're having a barbecue in the garden.", "example_vi": "Chúng tôi đang tổ chức tiệc nướng ngoài vườn.", "page_number": 71},
      {"word_number": 179, "word": "Beverage", "phonetic": "/ˈbev.ɚ.ɪdʒ/", "word_type": "noun", "meaning_vi": "Đồ uống, thức uống", "sound_bridge": "Bé vờ rên rỉ đòi uống đồ uống nước ngọt.", "definition_en": "a drink, especially one other than water", "example_en": "Hot beverages include tea and coffee.", "example_vi": "Đồ uống nóng bao gồm trà và cà phê.", "page_number": 71},
      {"word_number": 180, "word": "Culinary", "phonetic": "/ˈkʌl.ə.ner.i/", "word_type": "adjective", "meaning_vi": "Thuộc về ẩm thực, nấu nướng", "sound_bridge": "Cả làng nể tài nghệ nấu nướng ẩm thực của bác Ba.", "definition_en": "of or for cooking or the kitchen", "example_en": "She went to France to attend a culinary school.", "example_vi": "Cô ấy sang Pháp để theo học trường dạy nấu ăn ẩm thực.", "page_number": 71},
      {"word_number": 181, "word": "Flavor", "phonetic": "/ˈfleɪ.vɚ/", "word_type": "noun", "meaning_vi": "Hương vị", "sound_bridge": "Phải lấy vợ khéo tay để nấu món ăn tròn hương vị.", "definition_en": "the distinctive taste of a food or drink", "example_en": "Mint gives this ice cream a great flavor.", "example_vi": "Bạc hà mang lại cho món kem này một hương vị tuyệt vời.", "page_number": 71},
      {"word_number": 182, "word": "Freeze", "phonetic": "/friːz/", "word_type": "verb", "meaning_vi": "Đóng băng, đông lạnh", "sound_bridge": "Phi rủ bạn trượt băng trên mặt hồ đóng băng.", "definition_en": "be turned into ice or another solid as a result of extreme cold", "example_en": "Water freezes at 0 degrees Celsius.", "example_vi": "Nước đóng băng ở 0 độ C.", "page_number": 72},
      {"word_number": 183, "word": "Grill", "phonetic": "/ɡrɪl/", "word_type": "verb", "meaning_vi": "Nướng (bằng vỉ)", "sound_bridge": "Gà ri lấm lem bị đưa lên vỉ nướng than hồng.", "definition_en": "cook (something) using a grill", "example_en": "Grill the fish for five minutes on each side.", "example_vi": "Nướng cá trong năm phút mỗi mặt.", "page_number": 72},
      {"word_number": 184, "word": "Ingredient", "phonetic": "/ɪnˈɡriː.di.ənt/", "word_type": "noun", "meaning_vi": "Nguyên liệu, thành phần", "sound_bridge": "In danh sách nguyên liệu cần mua cho món phở.", "definition_en": "any of the foods or substances that are combined to make a particular dish", "example_en": "Fresh herbs are the main ingredient.", "example_vi": "Các loại rau thơm tươi là nguyên liệu chính.", "page_number": 72},
      {"word_number": 185, "word": "Kettle", "phonetic": "/ˈket̬.əl/", "word_type": "noun", "meaning_vi": "Ấm đun nước", "sound_bridge": "Kéo tời nâng ấm đun nước sôi sùng sục.", "definition_en": "a container or device in which water is boiled", "example_en": "I'll put the kettle on for some tea.", "example_vi": "Tôi sẽ đặt ấm đun nước để pha chút trà.", "page_number": 72},
      {"word_number": 186, "word": "Mixture", "phonetic": "/ˈmɪks.tʃɚ/", "word_type": "noun", "meaning_vi": "Hỗn hợp", "sound_bridge": "Mít chín trộn sữa tạo thành hỗn hợp sinh tố thơm phức.", "definition_en": "a substance made by mixing other substances together", "example_en": "Pour the cake mixture into the tin.", "example_vi": "Đổ hỗn hợp bột bánh vào khuôn.", "page_number": 72},
      {"word_number": 187, "word": "Mix-up", "phonetic": "/ˈmɪks.ʌp/", "word_type": "noun", "meaning_vi": "Sự nhầm lẫn, lộn xộn", "sound_bridge": "Mít sập tiệm vì sự nhầm lẫn đơn đặt hàng.", "definition_en": "a state of confusion; a muddle or mistake", "example_en": "There was a mix-up with our table reservation.", "example_vi": "Đã có sự nhầm lẫn về việc đặt bàn của chúng tôi.", "page_number": 73},
      {"word_number": 188, "word": "Refrigerator", "phonetic": "/rɪˈfrɪdʒ.ə.reɪ.t̬ɚ/", "word_type": "noun", "meaning_vi": "Tủ lạnh", "sound_bridge": "Ri phi vào bếp lục tủ lạnh tìm đồ ăn đêm.", "definition_en": "an appliance or compartment which is artificially kept cool and used to store food and drink", "example_en": "Store the milk in the refrigerator.", "example_vi": "Hãy cất sữa vào trong tủ lạnh.", "page_number": 73},
      {"word_number": 189, "word": "Rib", "phonetic": "/rɪb/", "word_type": "noun", "meaning_vi": "Sườn, xương sườn", "sound_bridge": "Ri bốc miếng sườn nướng mật ong béo ngậy.", "definition_en": "a cut of meat including one or more of the ribs", "example_en": "We ordered a rack of pork ribs.", "example_vi": "Chúng tôi đã gọi một dẻ sườn heo nướng.", "page_number": 73},
      {"word_number": 190, "word": "Roast", "phonetic": "/roʊst/", "word_type": "verb", "meaning_vi": "Quay, nướng (trong lò)", "sound_bridge": "Rủ ông cậu ăn món gà quay vàng giòn.", "definition_en": "cook (food, especially meat) by prolonged exposure to heat in an oven or over a fire", "example_en": "Roast the chicken for one hour.", "example_vi": "Quay con gà trong một giờ.", "page_number": 73},
      {"word_number": 191, "word": "Salty", "phonetic": "/ˈsɑːl.t̬i/", "word_type": "adjective", "meaning_vi": "Mặn", "sound_bridge": "Sợ tí mồ hôi rơi vào làm món canh bị mặn.", "definition_en": "tasting of, containing, or preserved with salt", "example_en": "The soup is a bit too salty.", "example_vi": "Món súp này hơi bị mặn quá.", "page_number": 73},
      {"word_number": 192, "word": "Sample", "phonetic": "/ˈsæm.pəl/", "word_type": "noun", "meaning_vi": "Mẫu thử", "sound_bridge": "Săn bồ tặng cho mẫu thử nước hoa mới ra mắt.", "definition_en": "a small part or quantity intended to show what the whole is like", "example_en": "They gave out free food samples.", "example_vi": "Họ đã phát những mẫu đồ ăn thử miễn phí.", "page_number": 74},
      {"word_number": 193, "word": "Spice", "phonetic": "/spaɪs/", "word_type": "noun", "meaning_vi": "Gia vị", "sound_bridge": "Sợ phai mùi thơm của các loại gia vị thượng hạng.", "definition_en": "an aromatic or pungent vegetable substance used to flavor food", "example_en": "Indian food uses a lot of spices.", "example_vi": "Món ăn Ấn Độ sử dụng rất nhiều loại gia vị.", "page_number": 74},
      {"word_number": 194, "word": "Steam", "phonetic": "/stiːm/", "word_type": "noun", "meaning_vi": "Hơi nước, món hấp", "sound_bridge": "Sợ tím tái mặt vì hơi nước nóng bốc lên từ nồi cơm.", "definition_en": "the vapor into which water is converted when heated", "example_en": "Steam rose from the hot bowl of soup.", "example_vi": "Hơi nước bốc lên từ bát súp nóng hổi.", "page_number": 74},
      {"word_number": 195, "word": "Stove", "phonetic": "/stoʊv/", "word_type": "noun", "meaning_vi": "Bếp lò", "sound_bridge": "Sợ tối nên bật lửa thắp sáng bếp lò ấm cúng.", "definition_en": "an apparatus for cooking or heating that operates by burning fuel or using electricity", "example_en": "Turn off the stove after cooking.", "example_vi": "Tắt bếp lò sau khi nấu xong nhé.", "page_number": 74},
      {"word_number": 196, "word": "Taste", "phonetic": "/teɪst/", "word_type": "verb", "meaning_vi": "Nếm, có vị", "sound_bridge": "Tây sợ nếm vị cay nồng của ớt hiểm Việt Nam.", "definition_en": "perceive or experience the flavor of", "example_en": "Taste the soup to see if it needs salt.", "example_vi": "Hãy nếm thử món súp xem có cần thêm muối không.", "page_number": 74},
      {"word_number": 197, "word": "Toast", "phonetic": "/toʊst/", "word_type": "noun", "meaning_vi": "Bánh mì nướng, nâng ly chúc mừng", "sound_bridge": "Tôi sợ bánh mì nướng bị cháy đen cạnh viền.", "definition_en": "sliced bread browned on both sides by exposure to radiant heat", "example_en": "I had buttered toast for breakfast.", "example_vi": "Tôi đã ăn bánh mì nướng bơ cho bữa sáng.", "page_number": 75}
    ]
  },

  # UNIT 8: Education 1 (29 từ, trang 79-85)
  {
    "unit": 8, "unit_title": "Education 1", "category": "Education",
    "words": [
      {"word_number": 198, "word": "Access", "phonetic": "/ˈæk.ses/", "word_type": "noun", "meaning_vi": "Quyền truy cập, lối vào", "sound_bridge": "Ăn kẹo sét đánh trúng cổng truy cập thư viện.", "definition_en": "the means or opportunity to approach or enter a place", "example_en": "Students have free access to the internet.", "example_vi": "Học sinh có quyền truy cập internet miễn phí.", "page_number": 79},
      {"word_number": 199, "word": "Blackboard", "phonetic": "/ˈblæk.bɔːrd/", "word_type": "noun", "meaning_vi": "Bảng đen", "sound_bridge": "Bà lác mắt nhìn chữ viết trên bảng đen lớn.", "definition_en": "a large board with a smooth dark surface used in classrooms for writing with chalk", "example_en": "The teacher wrote the math problem on the blackboard.", "example_vi": "Giáo viên đã viết bài toán lên bảng đen.", "page_number": 79},
      {"word_number": 200, "word": "Uniform", "phonetic": "/ˈjuː.nə.fɔːrm/", "word_type": "noun", "meaning_vi": "Đồng phục", "sound_bridge": "Du hí nơi phồn hoa nhớ mặc đồng phục trường.", "definition_en": "the distinctive clothing worn by members of the same organization or school", "example_en": "All pupils must wear school uniform.", "example_vi": "Tất cả học sinh đều phải mặc đồng phục trường.", "page_number": 79},
      {"word_number": 201, "word": "Classmate", "phonetic": "/ˈklæs.meɪt/", "word_type": "noun", "meaning_vi": "Bạn cùng lớp", "sound_bridge": "Cả làng mê tít tính hòa đồng của bạn cùng lớp.", "definition_en": "a fellow member of a class at school, college, or university", "example_en": "He invited all his classmates to his birthday.", "example_vi": "Cậu ấy đã mời tất cả bạn cùng lớp đến sinh nhật.", "page_number": 79},
      {"word_number": 202, "word": "Degree", "phonetic": "/dɪˈɡriː/", "word_type": "noun", "meaning_vi": "Bằng cấp, độ", "sound_bridge": "Đi gửi tấm bằng tốt nghiệp đại học về quê cho bố mẹ.", "definition_en": "an academic rank conferred by a college or university after examination", "example_en": "She holds a master's degree in economics.", "example_vi": "Cô ấy có bằng thạc sĩ kinh tế.", "page_number": 79},
      {"word_number": 203, "word": "Elementary", "phonetic": "/ˌel.əˈmen.t̬ɚ.i/", "word_type": "adjective", "meaning_vi": "Tiểu học, cơ bản", "sound_bridge": "Em lại mượn tập vở tiểu học của em gái.", "definition_en": "relating to the basic or primary elements of a subject", "example_en": "He teaches at an elementary school.", "example_vi": "Anh ấy giảng dạy tại một trường tiểu học.", "page_number": 80},
      {"word_number": 204, "word": "Essay", "phonetic": "/ˈes.eɪ/", "word_type": "noun", "meaning_vi": "Bài luận", "sound_bridge": "Em say mê viết bài luận văn học đạt điểm 10.", "definition_en": "a short piece of writing on a particular subject", "example_en": "We have to write an essay on climate change.", "example_vi": "Chúng tôi phải viết một bài luận về biến đổi khí hậu.", "page_number": 80},
      {"word_number": 205, "word": "Examine", "phonetic": "/ɪɡˈzæm.ɪn/", "word_type": "verb", "meaning_vi": "Khám xét, kiểm tra", "sound_bridge": "Ích kỷ giấu bài kiểm tra khi thầy giáo đến kiểm tra.", "definition_en": "inspect (someone or something) thoroughly in order to determine their nature or condition", "example_en": "The doctor examined the patient carefully.", "example_vi": "Bác sĩ đã kiểm tra bệnh nhân rất cẩn thận.", "page_number": 80},
      {"word_number": 206, "word": "Fail", "phonetic": "/feɪl/", "word_type": "verb", "meaning_vi": "Trượt, thi hỏng", "sound_bridge": "Phải thi lại vì trượt môn toán khó nhằn.", "definition_en": "be unsuccessful in achieving one's goal or in an exam", "example_en": "He worked hard so he wouldn't fail the test.", "example_vi": "Cậu ấy học chăm chỉ để không bị trượt bài kiểm tra.", "page_number": 80},
      {"word_number": 207, "word": "Holiday", "phonetic": "/ˈhɑː.lə.deɪ/", "word_type": "noun", "meaning_vi": "Kỳ nghỉ", "sound_bridge": "Hồ lộng gió đón kỳ nghỉ hè tuyệt vời.", "definition_en": "an extended period of leisure and recreation", "example_en": "Where are you going for summer holiday?", "example_vi": "Bạn sẽ đi đâu vào kỳ nghỉ hè?", "page_number": 80},
      {"word_number": 208, "word": "Improve", "phonetic": "/ɪmˈpruːv/", "word_type": "verb", "meaning_vi": "Cải thiện, tiến bộ", "sound_bridge": "In phao rủ bạn cùng học để cải thiện điểm số.", "definition_en": "make or become better", "example_en": "Reading daily helps improve your vocabulary.", "example_vi": "Đọc sách hàng ngày giúp cải thiện vốn từ vựng của bạn.", "page_number": 81},
      {"word_number": 209, "word": "Layout", "phonetic": "/ˈleɪ.aʊt/", "word_type": "noun", "meaning_vi": "Bố cục, cách trình bày", "sound_bridge": "Lấy áo thiết kế bố cục trang bìa tạp chí.", "definition_en": "the way in which the parts of something are arranged or laid out", "example_en": "The layout of the classroom is spacious.", "example_vi": "Bố cục của phòng học rất rộng rãi.", "page_number": 81},
      {"word_number": 210, "word": "Lecture", "phonetic": "/ˈlek.tʃɚ/", "word_type": "noun", "meaning_vi": "Bài giảng", "sound_bridge": "Lệ chứa chan khi nghe bài giảng ý nghĩa của thầy.", "definition_en": "an educational talk to an audience, especially to students in a university", "example_en": "The professor gave an interesting lecture.", "example_vi": "Giáo sư đã có một bài giảng rất thú vị.", "page_number": 81},
      {"word_number": 211, "word": "Mentor", "phonetic": "/ˈmen.tɔːr/", "word_type": "noun", "meaning_vi": "Người hướng dẫn, cố vấn", "sound_bridge": "Men theo con đường thành công nhờ có người hướng dẫn tận tâm.", "definition_en": "an experienced and trusted adviser", "example_en": "My mentor gave me invaluable advice.", "example_vi": "Người cố vấn của tôi đã cho tôi lời khuyên vô giá.", "page_number": 81},
      {"word_number": 212, "word": "Mistake", "phonetic": "/mɪˈsteɪk/", "word_type": "noun", "meaning_vi": "Lỗi lầm, sai sót", "sound_bridge": "Mít tếch đi vì phạm lỗi lầm lớn trong bài thi.", "definition_en": "an action or judgment that is misguided or wrong", "example_en": "Everyone makes mistakes sometimes.", "example_vi": "Ai cũng có lúc mắc phải sai lầm.", "page_number": 81},
      {"word_number": 213, "word": "Nursery", "phonetic": "/ˈnɝː.sɚ.i/", "word_type": "noun", "meaning_vi": "Nhà trẻ", "sound_bridge": "Nơi sợ trẻ con khóc là nhà trẻ mẫu giáo.", "definition_en": "a room in a house for the special use of young children", "example_en": "She drops her daughter at nursery every morning.", "example_vi": "Cô ấy đưa con gái đến nhà trẻ mỗi sáng.", "page_number": 82},
      {"word_number": 214, "word": "Object", "phonetic": "/ˈɑːb.dʒɪkt/", "word_type": "noun", "meaning_vi": "Đồ vật, mục tiêu", "sound_bridge": "Ông bực mình vì đồ vật bị vứt lung tung trong lớp.", "definition_en": "a material thing that can be seen and touched", "example_en": "Look at the object on the desk.", "example_vi": "Hãy nhìn vào đồ vật trên bàn kìa.", "page_number": 82},
      {"word_number": 215, "word": "Outstanding", "phonetic": "/ˌaʊtˈstæn.dɪŋ/", "word_type": "adjective", "meaning_vi": "Xuất sắc, nổi bật", "sound_bridge": "Ao sâu tắm đứng vẫn nổi bật vì học sinh xuất sắc.", "definition_en": "exceptionally good; clearly noticeable", "example_en": "She is an outstanding student in our school.", "example_vi": "Cô ấy là một học sinh xuất sắc của trường chúng tôi.", "page_number": 82},
      {"word_number": 216, "word": "Overview", "phonetic": "/ˈoʊ.vɚ.vjuː/", "word_type": "noun", "meaning_vi": "Tổng quan", "sound_bridge": "Ở vừa vặn trên cao nhìn được cái nhìn tổng quan toàn cảnh.", "definition_en": "a general review or summary of a subject", "example_en": "The teacher gave an overview of the syllabus.", "example_vi": "Giáo viên đã đưa ra cái nhìn tổng quan về giáo trình.", "page_number": 82},
      {"word_number": 217, "word": "Practical", "phonetic": "/ˈpræk.tɪ.kəl/", "word_type": "adjective", "meaning_vi": "Thực tế, thực hành", "sound_bridge": "Phải rắc tiêu cay vào món ăn mới có kinh nghiệm thực tế.", "definition_en": "of or concerned with the actual doing or use of something", "example_en": "We need more practical training.", "example_vi": "Chúng ta cần nhiều buổi đào tạo thực hành hơn.", "page_number": 82},
      {"word_number": 218, "word": "Practice", "phonetic": "/ˈpræk.tɪs/", "word_type": "verb", "meaning_vi": "Luyện tập, thực hành", "sound_bridge": "Phải rác tai nghe nhạc để luyện tập phát âm tiếng Anh.", "definition_en": "perform (an activity) or exercise (a skill) repeatedly or regularly in order to improve or maintain one's proficiency", "example_en": "Practice speaking English every single day.", "example_vi": "Hãy luyện tập nói tiếng Anh mỗi ngày.", "page_number": 83},
      {"word_number": 219, "word": "Primary", "phonetic": "/ˈpraɪ.mer.i/", "word_type": "adjective", "meaning_vi": "Chính, tiểu học", "sound_bridge": "Phải rải mì chính vào nồi là nhiệm vụ chính của đầu bếp.", "definition_en": "of chief importance; principal", "example_en": "Primary education is compulsory.", "example_vi": "Giáo dục tiểu học là bắt buộc.", "page_number": 83},
      {"word_number": 220, "word": "Principal", "phonetic": "/ˈprɪn.sə.pəl/", "word_type": "noun", "meaning_vi": "Hiệu trưởng", "sound_bridge": "Phải rủ bồ đi gặp thầy hiệu trưởng xin phép.", "definition_en": "the head of a school, college, or other educational institution", "example_en": "The principal welcomed the new students.", "example_vi": "Thầy hiệu trưởng đã chào đón các tân học sinh.", "page_number": 83},
      {"word_number": 221, "word": "Quantify", "phonetic": "/ˈkwɑːn.t̬ə.faɪ/", "word_type": "verb", "meaning_vi": "Định lượng, lượng hóa", "sound_bridge": "Quản lý phai nhạt dần nếu không định lượng được kết quả.", "definition_en": "express or measure the quantity of", "example_en": "It is difficult to quantify the success.", "example_vi": "Rất khó để định lượng sự thành công.", "page_number": 83},
      {"word_number": 222, "word": "Regardless", "phonetic": "/rɪˈɡɑːrd.ləs/", "word_type": "adverb", "meaning_vi": "Bất chấp, bất kể", "sound_bridge": "Ri gạt lọt lưới bất chấp sự ngăn cản của thủ môn.", "definition_en": "without paying attention to the present situation; anyway", "example_en": "He continued studying regardless of his fatigue.", "example_vi": "Cậu ấy vẫn tiếp tục học bất chấp sự mệt mỏi.", "page_number": 83},
      {"word_number": 223, "word": "Register", "phonetic": "/ˈredʒ.ə.stɚ/", "word_type": "verb", "meaning_vi": "Đăng ký", "sound_bridge": "Rẽ sang tiệm sách đăng ký khóa học tiếng Anh mới.", "definition_en": "enter or record on an official list or directory", "example_en": "Register for the course before Friday.", "example_vi": "Hãy đăng ký khóa học trước thứ Sáu.", "page_number": 84},
      {"word_number": 224, "word": "Revise", "phonetic": "/rɪˈvaɪz/", "word_type": "verb", "meaning_vi": "Ôn tập, sửa đổi", "sound_bridge": "Ri vài lần ôn tập trước khi bước vào phòng thi.", "definition_en": "re-examine and make alterations to (written or printed matter)", "example_en": "I must revise for my exams tonight.", "example_vi": "Tôi phải ôn tập cho kỳ thi tối nay.", "page_number": 84},
      {"word_number": 225, "word": "Textbook", "phonetic": "/ˈtekst.bʊk/", "word_type": "noun", "meaning_vi": "Sách giáo khoa", "sound_bridge": "Tết bận rộn vẫn mua đủ sách giáo khoa cho con.", "definition_en": "a book used as a standard work for the study of a particular subject", "example_en": "Open your textbook to page 50.", "example_vi": "Hãy mở sách giáo khoa ra trang 50.", "page_number": 84},
      {"word_number": 226, "word": "Project", "phonetic": "/ˈprɑː.dʒekt/", "word_type": "noun", "meaning_vi": "Dự án, đồ án", "sound_bridge": "Đi bộ ra tầng trệt để suy nghĩ về dự án học tập.", "definition_en": "an individual or collaborative enterprise planned to achieve an aim", "example_en": "My team is working on a science project.", "example_vi": "Nhóm của tôi đang làm một dự án khoa học.", "page_number": 85}
    ]
  },

  # UNIT 9: Education 2 (25 từ, trang 89-94)
  {
    "unit": 9, "unit_title": "Education 2", "category": "Education",
    "words": [
      {"word_number": 227, "word": "Abroad", "phonetic": "/əˈbrɑːd/", "word_type": "adverb", "meaning_vi": "Ở nước ngoài, ra nước ngoài", "sound_bridge": "Ở bờ rào nhìn máy bay bay đi du học nước ngoài.", "definition_en": "in or to a foreign country or countries", "example_en": "She wants to study abroad next year.", "example_vi": "Cô ấy muốn đi du học nước ngoài vào năm tới.", "page_number": 89},
      {"word_number": 228, "word": "Absent", "phonetic": "/ˈæb.sənt/", "word_type": "adjective", "meaning_vi": "Vắng mặt", "sound_bridge": "Ăn bớt tiền bị phạt vắng mặt trong buổi lễ khen thưởng.", "definition_en": "not present in a place, at an occasion, or as part of something", "example_en": "Why were you absent from school yesterday?", "example_vi": "Tại sao hôm qua bạn lại vắng mặt ở trường?", "page_number": 89},
      {"word_number": 229, "word": "Abstract", "phonetic": "/ˈæb.strækt/", "word_type": "adjective", "meaning_vi": "Trừu tượng", "sound_bridge": "Ăn bắp tróc vỏ nhìn bức tranh trừu tượng độc đáo.", "definition_en": "existing in thought or as an idea but not having a physical or concrete existence", "example_en": "Abstract art can be hard to understand.", "example_vi": "Nghệ thuật trừu tượng có thể khó hiểu.", "page_number": 89},
      {"word_number": 230, "word": "Adjacent", "phonetic": "/əˈdʒeɪ.sənt/", "word_type": "adjective", "meaning_vi": "Kế bên, liền kề", "sound_bridge": "Ở dãy số bên cạnh là lớp học liền kề.", "definition_en": "next to or adjoining something else", "example_en": "The library is adjacent to the science lab.", "example_vi": "Thư viện nằm liền kề với phòng thí nghiệm khoa học.", "page_number": 89},
      {"word_number": 231, "word": "Advance", "phonetic": "/ədˈvæns/", "word_type": "verb", "meaning_vi": "Tiến bộ, nâng cao", "sound_bridge": "Ăn van xin để được tiến bộ trong kỳ học này.", "definition_en": "move forward, typically in a purposeful way", "example_en": "Technology continues to advance rapidly.", "example_vi": "Công nghệ tiếp tục tiến bộ một cách nhanh chóng.", "page_number": 89},
      {"word_number": 232, "word": "Afterwards", "phonetic": "/ˈæf.tɚ.wɚdz/", "word_type": "adverb", "meaning_vi": "Sau đó", "sound_bridge": "Ăn phở tơ vương rồi sau đó đi học bài.", "definition_en": "at a later or subsequent time", "example_en": "We had lunch and went to the library afterwards.", "example_vi": "Chúng tôi ăn trưa và sau đó đến thư viện.", "page_number": 90},
      {"word_number": 233, "word": "Assist", "phonetic": "/əˈsɪst/", "word_type": "verb", "meaning_vi": "Hỗ trợ, giúp đỡ", "sound_bridge": "Ơ sít vào đây để tớ hỗ trợ giảng bài cho.", "definition_en": "help (someone), typically by doing a share of the work", "example_en": "Can you assist me with my homework?", "example_vi": "Bạn có thể giúp tôi làm bài tập về nhà không?", "page_number": 90},
      {"word_number": 234, "word": "Basis", "phonetic": "/ˈbeɪ.sɪs/", "word_type": "noun", "meaning_vi": "Nền tảng, cơ sở", "sound_bridge": "Bà xích con chó tạo cơ sở bảo vệ an toàn cho nhà.", "definition_en": "the underlying support or foundation for an idea, argument, or process", "example_en": "This theory forms the basis of modern physics.", "example_vi": "Lý thuyết này tạo thành nền tảng của vật lý hiện đại.", "page_number": 90},
      {"word_number": 235, "word": "Common", "phonetic": "/ˈkɑː.mən/", "word_type": "adjective", "meaning_vi": "Phổ biến, chung", "sound_bridge": "Cỏ mọc quanh trường là cảnh tượng rất phổ biến.", "definition_en": "occurring, found, or done often; prevalent", "example_en": "It is a common mistake among learners.", "example_vi": "Đó là một lỗi sai phổ biến của người học.", "page_number": 90},
      {"word_number": 236, "word": "Concentrate", "phonetic": "/ˈkɑːn.sən.treɪt/", "word_type": "verb", "meaning_vi": "Tập trung", "sound_bridge": "Con sợ trễ xe nên phải tập trung học nhanh.", "definition_en": "focus one's full attention or intellect on something", "example_en": "I need quiet so I can concentrate on my studies.", "example_vi": "Tôi cần yên tĩnh để có thể tập trung vào việc học.", "page_number": 90},
      {"word_number": 237, "word": "Concern", "phonetic": "/kənˈsɝːn/", "word_type": "noun", "meaning_vi": "Mối lo ngại, sự quan tâm", "sound_bridge": "Còn sờn rách bài thi làm dấy lên mối lo ngại trượt môn.", "definition_en": "anxiety; worry", "example_en": "The teacher expressed concern about his grades.", "example_vi": "Giáo viên bày tỏ sự lo ngại về điểm số của cậu ấy.", "page_number": 91},
      {"word_number": 238, "word": "Conclude", "phonetic": "/kənˈkluːd/", "word_type": "verb", "meaning_vi": "Kết luận", "sound_bridge": "Còn lùi bước thì không thể kết luận bài toán hoàn chỉnh.", "definition_en": "bring (something) to an end", "example_en": "To conclude, I would like to thank you all.", "example_vi": "Để kết luận, tôi xin gửi lời cảm ơn tới tất cả các bạn.", "page_number": 91},
      {"word_number": 239, "word": "Concrete", "phonetic": "/ˈkɑːn.kriːt/", "word_type": "adjective", "meaning_vi": "Cụ thể, bê tông", "sound_bridge": "Còn kẹp rơm vào bê tông để có ví dụ cụ thể.", "definition_en": "existing in a material or physical form; not abstract", "example_en": "Give me a concrete example of this rule.", "example_vi": "Hãy cho tôi một ví dụ cụ thể về quy tắc này.", "page_number": 91},
      {"word_number": 240, "word": "Course", "phonetic": "/kɔːrs/", "word_type": "noun", "meaning_vi": "Khóa học", "sound_bridge": "Cơm sườn ngon ăn sau khi hoàn thành khóa học.", "definition_en": "a series of lectures or lessons in a particular subject", "example_en": "I enrolled in an online English course.", "example_vi": "Tôi đã đăng ký một khóa học tiếng Anh trực tuyến.", "page_number": 91},
      {"word_number": 241, "word": "Deadline", "phonetic": "/ˈded.laɪn/", "word_type": "noun", "meaning_vi": "Hạn chót", "sound_bridge": "Để đè lên bàn hạn chót nộp bài tập lớn.", "definition_en": "the latest time or date by which something should be completed", "example_en": "The deadline for the assignment is tomorrow.", "example_vi": "Hạn chót nộp bài tập là ngày mai.", "page_number": 91},
      {"word_number": 242, "word": "Debate", "phonetic": "/dɪˈbeɪt/", "word_type": "noun", "meaning_vi": "Cuộc tranh luận", "sound_bridge": "Đi bế em nhỏ mà vẫn tham gia cuộc tranh luận sôi nổi.", "definition_en": "a formal discussion on a particular topic in a public meeting or legislative assembly", "example_en": "We had a lively debate in class today.", "example_vi": "Hôm nay chúng tôi đã có một cuộc tranh luận sôi nổi trong lớp.", "page_number": 92},
      {"word_number": 243, "word": "Diagram", "phonetic": "/ˈdaɪ.ə.ɡræm/", "word_type": "noun", "meaning_vi": "Biểu đồ, sơ đồ", "sound_bridge": "Đáy rương cất giữ sơ đồ kho báu học tập.", "definition_en": "a simplified drawing showing the appearance, structure, or workings of something", "example_en": "Draw a diagram to explain the process.", "example_vi": "Hãy vẽ một sơ đồ để giải thích quy trình.", "page_number": 92},
      {"word_number": 244, "word": "Draft", "phonetic": "/dræft/", "word_type": "noun", "meaning_vi": "Bản nháp", "sound_bridge": "Đưa rác ra ngoài sau khi viết xong bản nháp bài luận.", "definition_en": "a preliminary version of a piece of writing", "example_en": "This is just a rough draft of my paper.", "example_vi": "Đây chỉ là bản nháp sơ bộ bài báo của tôi.", "page_number": 92},
      {"word_number": 245, "word": "Eligible", "phonetic": "/ˈel.ə.dʒə.bəl/", "word_type": "adjective", "meaning_vi": "Đủ điều kiện, đủ tư cách", "sound_bridge": "Em lấy giấy chứng nhận đủ điều kiện nhận học bổng.", "definition_en": "having the right to do or obtain something; satisfying the appropriate conditions", "example_en": "Only top students are eligible for this scholarship.", "example_vi": "Chỉ những học sinh giỏi nhất mới đủ điều kiện nhận học bổng này.", "page_number": 92},
      {"word_number": 246, "word": "Error", "phonetic": "/ˈer.ɚ/", "word_type": "noun", "meaning_vi": "Lỗi sai", "sound_bridge": "Em rờ vào bài thi tìm ra lỗi sai toán học.", "definition_en": "a mistake", "example_en": "The computer program reported a syntax error.", "example_vi": "Chương trình máy tính báo một lỗi cú pháp.", "page_number": 92},
      {"word_number": 247, "word": "Hall", "phonetic": "/hɑːl/", "word_type": "noun", "meaning_vi": "Hội trường, sảnh lớn", "sound_bridge": "Hồ lớn bên cạnh hội trường tổ chức lễ tốt nghiệp.", "definition_en": "a large room used for meetings, concerts, or other events", "example_en": "The graduation ceremony will take place in the main hall.", "example_vi": "Lễ tốt nghiệp sẽ diễn ra tại hội trường chính.", "page_number": 93},
      {"word_number": 248, "word": "Integral", "phonetic": "/ˈɪn.t̬ə.ɡrəl/", "word_type": "adjective", "meaning_vi": "Thiết yếu, không thể thiếu", "sound_bridge": "In tờ giấy khen cho phần đóng góp thiết yếu của em.", "definition_en": "necessary to make a whole complete; essential or fundamental", "example_en": "Self-study is an integral part of learning.", "example_vi": "Tự học là một phần thiết yếu của việc học tập.", "page_number": 93},
      {"word_number": 249, "word": "Library", "phonetic": "/ˈlaɪ.brer.i/", "word_type": "noun", "meaning_vi": "Thư viện", "sound_bridge": "Lại bước vào thư viện đọc sách yên tĩnh.", "definition_en": "a building or room containing collections of books", "example_en": "Silence must be maintained in the library.", "example_vi": "Phải giữ trật tự im lặng trong thư viện.", "page_number": 93},
      {"word_number": 250, "word": "Priority", "phonetic": "/praɪˈɔːr.ə.t̬i/", "word_type": "noun", "meaning_vi": "Sự ưu tiên", "sound_bridge": "Phải rải ô tô đỗ đúng nơi ưu tiên cho xe buýt học sinh.", "definition_en": "the fact or condition of being regarded or treated as more important", "example_en": "Education is our top priority.", "example_vi": "Giáo dục là ưu tiên hàng đầu của chúng tôi.", "page_number": 93},
      {"word_number": 251, "word": "Private", "phonetic": "/ˈpraɪ.vət/", "word_type": "adjective", "meaning_vi": "Tư nhân, riêng tư", "sound_bridge": "Phải ra về phòng riêng tư để tập trung ôn thi.", "definition_en": "belonging to or for the use of one particular person or group of people only", "example_en": "He attends a private school.", "example_vi": "Cậu ấy theo học tại một trường tư thục.", "page_number": 93}
    ]
  },

  # UNIT 10: Education 3 (29 từ, trang 98-104)
  {
    "unit": 10, "unit_title": "Education 3", "category": "Education",
    "words": [
      {"word_number": 252, "word": "Academic", "phonetic": "/ˌæk.əˈdem.ɪk/", "word_type": "adjective", "meaning_vi": "Thuộc học thuật, học viện", "sound_bridge": "Ăn cá đem lại nhiều thành tích học thuật cao.", "definition_en": "relating to education and scholarship", "example_en": "She achieved high academic standards.", "example_vi": "Cô ấy đạt được những tiêu chuẩn học thuật rất cao.", "page_number": 98},
      {"word_number": 253, "word": "Acknowledge", "phonetic": "/əkˈnɑː.lɪdʒ/", "word_type": "verb", "meaning_vi": "Công nhận, thừa nhận", "sound_bridge": "Ơ con nợ biết công nhận sự giúp đỡ của bạn bè.", "definition_en": "accept or admit the existence or truth of", "example_en": "He acknowledged his contribution to the study.", "example_vi": "Anh ấy công nhận sự đóng góp của mình cho nghiên cứu.", "page_number": 98},
      {"word_number": 254, "word": "Assignment", "phonetic": "/əˈsaɪn.mənt/", "word_type": "noun", "meaning_vi": "Bài tập phân công", "sound_bridge": "Ơ say sưa làm bài tập phân công của nhóm.", "definition_en": "a task or piece of work assigned to someone as part of a job or course of study", "example_en": "Submit your assignment on Google Classroom.", "example_vi": "Hãy nộp bài tập phân công của bạn lên Google Classroom.", "page_number": 98},
      {"word_number": 255, "word": "Ballet", "phonetic": "/bælˈeɪ/", "word_type": "noun", "meaning_vi": "Múa ba lê", "sound_bridge": "Ba lại xem tiết mục múa ba lê nghệ thuật của con.", "definition_en": "an artistic dance form using music and scenery to convey a story", "example_en": "She has been practicing ballet since childhood.", "example_vi": "Cô ấy đã tập múa ba lê từ thuở nhỏ.", "page_number": 98},
      {"word_number": 256, "word": "Biology", "phonetic": "/baɪˈɑː.lə.dʒi/", "word_type": "noun", "meaning_vi": "Môn sinh học", "sound_bridge": "Bà ốm lo lắng khi học môn sinh học về vi khuẩn.", "definition_en": "the study of living organisms", "example_en": "We dissected a frog in biology class.", "example_vi": "Chúng tôi đã mổ một con ếch trong tiết sinh học.", "page_number": 98},
      {"word_number": 257, "word": "Calculate", "phonetic": "/ˈkæl.kjə.leɪt/", "word_type": "verb", "meaning_vi": "Tính toán", "sound_bridge": "Cả làng kêu la vì tính toán hóa đơn phức tạp.", "definition_en": "determine (the amount or number of something) mathematically", "example_en": "Use a calculator to calculate the total score.", "example_vi": "Hãy dùng máy tính để tính toán tổng điểm.", "page_number": 99},
      {"word_number": 258, "word": "Chemistry", "phonetic": "/ˈkem.ə.stri/", "word_type": "noun", "meaning_vi": "Môn hóa học", "sound_bridge": "Kèm theo sữa chua khi thí nghiệm môn hóa học.", "definition_en": "the branch of science that deals with the identification of substances", "example_en": "Chemistry is my favorite subject.", "example_vi": "Hóa học là môn học yêu thích nhất của tôi.", "page_number": 99},
      {"word_number": 259, "word": "Colleague", "phonetic": "/ˈkɑː.liːɡ/", "word_type": "noun", "meaning_vi": "Đồng nghiệp", "sound_bridge": "Có ly cà phê mời đồng nghiệp cùng thưởng thức.", "definition_en": "a person with whom one works in a profession or business", "example_en": "I discussed the plan with my colleagues.", "example_vi": "Tôi đã thảo luận kế hoạch với các đồng nghiệp.", "page_number": 99},
      {"word_number": 260, "word": "College", "phonetic": "/ˈkɑː.lɪdʒ/", "word_type": "noun", "meaning_vi": "Trường cao đẳng, đại học", "sound_bridge": "Cỏ mọc quanh khuôn viên trường đại học xanh tươi.", "definition_en": "an educational institution or establishment", "example_en": "He graduated from college last year.", "example_vi": "Cậu ấy đã tốt nghiệp đại học vào năm ngoái.", "page_number": 99},
      {"word_number": 261, "word": "Commensurate", "phonetic": "/kəˈmen.sjɚ.ət/", "word_type": "adjective", "meaning_vi": "Tương xứng", "sound_bridge": "Còn mềm xèo thì chưa tương xứng với yêu cầu bài thi.", "definition_en": "corresponding in size or degree; in proportion", "example_en": "Salary will be commensurate with experience.", "example_vi": "Mức lương sẽ tương xứng với kinh nghiệm làm việc.", "page_number": 99},
      {"word_number": 262, "word": "Committee", "phonetic": "/kəˈmɪt.i/", "word_type": "noun", "meaning_vi": "Ủy ban, hội đồng", "sound_bridge": "Có mít ngon hội đồng họp bàn thưởng cho học sinh giỏi.", "definition_en": "a group of people appointed for a specific function by a larger group and typically consisting of members of that group", "example_en": "The committee approved the new scholarship policy.", "example_vi": "Hội đồng đã phê duyệt chính sách học bổng mới.", "page_number": 100},
      {"word_number": 263, "word": "Council", "phonetic": "/ˈkaʊn.səl/", "word_type": "noun", "meaning_vi": "Hội đồng", "sound_bridge": "Con sợ họp hội đồng kỷ luật trường.", "definition_en": "an advisory, deliberative, or legislative body of people formally constituted", "example_en": "The student council organized the event.", "example_vi": "Hội đồng học sinh đã tổ chức sự kiện này.", "page_number": 100},
      {"word_number": 264, "word": "Department", "phonetic": "/dɪˈpɑːrt.mənt/", "word_type": "noun", "meaning_vi": "Khoa, phòng ban", "sound_bridge": "Đi qua bạt ngàn phòng học của khoa ngoại ngữ.", "definition_en": "a division of a large organization such as a government, university, or business", "example_en": "She works in the English Department.", "example_vi": "Cô ấy công tác tại Khoa Tiếng Anh.", "page_number": 100},
      {"word_number": 265, "word": "Diploma", "phonetic": "/dɪˈploʊ.mə/", "word_type": "noun", "meaning_vi": "Bằng cấp, chứng chỉ", "sound_bridge": "Đi phỏng vấn cầm chứng chỉ bằng cấp tự tin.", "definition_en": "a certificate awarded by an educational establishment to show that someone has successfully completed a course of study", "example_en": "He received his high school diploma.", "example_vi": "Cậu ấy đã nhận bằng tốt nghiệp trung học phổ thông.", "page_number": 100},
      {"word_number": 266, "word": "Graduate", "phonetic": "/ˈɡrædʒ.u.eɪt/", "word_type": "verb", "meaning_vi": "Tốt nghiệp", "sound_bridge": "Gà ra đường ăn mừng ngày lễ tốt nghiệp đại học.", "definition_en": "successfully complete an academic degree, course of training, or high school", "example_en": "She will graduate from university in June.", "example_vi": "Cô ấy sẽ tốt nghiệp đại học vào tháng Sáu.", "page_number": 100},
      {"word_number": 267, "word": "Handout", "phonetic": "/ˈhænd.aʊt/", "word_type": "noun", "meaning_vi": "Tài liệu phát tay", "sound_bridge": "Hát áo ướt khi phát tài liệu phát tay cho cả lớp.", "definition_en": "a document given to students or that contains information about a particular subject", "example_en": "Read the handout before the lecture starts.", "example_vi": "Hãy đọc tài liệu phát tay trước khi bài giảng bắt đầu.", "page_number": 101},
      {"word_number": 268, "word": "Honor", "phonetic": "/ˈɑː.nɚ/", "word_type": "noun", "meaning_vi": "Vinh dự, danh dự", "sound_bridge": "Ở nơi danh dự nhận bằng khen học sinh gương mẫu.", "definition_en": "high respect; great esteem", "example_en": "It is a great honor to receive this award.", "example_vi": "Thật là một vinh dự to lớn khi nhận được giải thưởng này.", "page_number": 101},
      {"word_number": 269, "word": "Institute", "phonetic": "/ˈɪn.stə.tuːt/", "word_type": "noun", "meaning_vi": "Học viện, viện nghiên cứu", "sound_bridge": "In sách tự học cho học viện ngôn ngữ quốc tế.", "definition_en": "a society or organization having a particular purpose or object, especially a scientific, educational, or social one", "example_en": "He works at the research institute.", "example_vi": "Anh ấy làm việc tại viện nghiên cứu.", "page_number": 101},
      {"word_number": 270, "word": "Merit", "phonetic": "/ˈmer.ɪt/", "word_type": "noun", "meaning_vi": "Công trạng, sự xuất sắc", "sound_bridge": "Mẹ rủ đi nhận học bổng công trạng khen thưởng.", "definition_en": "the quality of being particularly good or worthy, especially so as to deserve praise or reward", "example_en": "Scholarships are awarded purely on academic merit.", "example_vi": "Học bổng được trao hoàn toàn dựa trên sự xuất sắc trong học tập.", "page_number": 101},
      {"word_number": 271, "word": "Outline", "phonetic": "/ˈaʊt.laɪn/", "word_type": "noun", "meaning_vi": "Dàn ý, đề cương", "sound_bridge": "Ao lặn lội tìm đề cương dàn ý bài tập làm văn.", "definition_en": "a general description or plan giving the essential features of something but not the detail", "example_en": "Write an outline before writing the full essay.", "example_vi": "Hãy viết dàn ý trước khi viết toàn bộ bài luận.", "page_number": 101},
      {"word_number": 272, "word": "Philosophy", "phonetic": "/fɪˈlɑː.sə.fi/", "word_type": "noun", "meaning_vi": "Môn triết học", "sound_bridge": "Phi lo sợ khi học môn triết học Mác-Lênin.", "definition_en": "the study of the fundamental nature of knowledge, reality, and existence", "example_en": "He is majoring in Eastern philosophy.", "example_vi": "Anh ấy đang theo học chuyên ngành triết học phương Đông.", "page_number": 102},
      {"word_number": 273, "word": "Prerequisite", "phonetic": "/ˌpriːˈrek.wə.zɪt/", "word_type": "noun", "meaning_vi": "Điều kiện tiên quyết", "sound_bridge": "Phi rủ bạn hoàn thành điều kiện tiên quyết trước khi đăng ký môn.", "definition_en": "a thing that is required as a prior condition for something else to happen or exist", "example_en": "Math 101 is a prerequisite for this course.", "example_vi": "Môn Toán 101 là điều kiện tiên quyết cho khóa học này.", "page_number": 102},
      {"word_number": 274, "word": "Qualify", "phonetic": "/ˈkwɑː.lə.faɪ/", "word_type": "verb", "meaning_vi": "Đủ tiêu chuẩn, đủ điều kiện", "sound_bridge": "Quả ổi phai màu nhưng vẫn đủ tiêu chuẩn làm nước ép.", "definition_en": "be entitled to a particular benefit or privilege by fulfilling a necessary condition", "example_en": "You need high scores to qualify for the program.", "example_vi": "Bạn cần điểm số cao để đủ điều kiện tham gia chương trình.", "page_number": 102},
      {"word_number": 275, "word": "Research", "phonetic": "/rɪˈsɝːtʃ/", "word_type": "noun", "meaning_vi": "Nghiên cứu", "sound_bridge": "Ri sờ sợ khi tiến hành nghiên cứu khoa học đầu tay.", "definition_en": "the systematic investigation into and study of materials and sources in order to establish facts and reach new conclusions", "example_en": "She is doing research on cancer treatment.", "example_vi": "Cô ấy đang làm nghiên cứu về điều trị ung thư.", "page_number": 102},
      {"word_number": 276, "word": "Seminar", "phonetic": "/ˈsem.ə.nɑːr/", "word_type": "noun", "meaning_vi": "Hội thảo chuyên đề", "sound_bridge": "Sợ mì nở nên ăn nhanh trước giờ hội thảo chuyên đề.", "definition_en": "a conference or other meeting for discussion or training", "example_en": "Attend the seminar on digital learning tomorrow.", "example_vi": "Hãy tham dự hội thảo về học tập số vào ngày mai.", "page_number": 102},
      {"word_number": 277, "word": "Summary", "phonetic": "/ˈsʌm.ɚ.i/", "word_type": "noun", "meaning_vi": "Bản tóm tắt", "sound_bridge": "Săn mua được cuốn sách có bản tóm tắt rất hay.", "definition_en": "a brief statement or account of the main points of something", "example_en": "Write a brief summary of the reading passage.", "example_vi": "Hãy viết một bản tóm tắt ngắn gọn về đoạn văn vừa đọc.", "page_number": 103},
      {"word_number": 278, "word": "Terms", "phonetic": "/tɝːmz/", "word_type": "noun", "meaning_vi": "Thuật ngữ, học kỳ, điều khoản", "sound_bridge": "Tấm rèm che kín danh sách các thuật ngữ chuyên ngành.", "definition_en": "words or expressions used in relation to a particular subject", "example_en": "Learn all the scientific terms before the exam.", "example_vi": "Hãy học tất cả các thuật ngữ khoa học trước kỳ thi.", "page_number": 103},
      {"word_number": 279, "word": "Thesis", "phonetic": "/ˈθiː.sɪs/", "word_type": "noun", "meaning_vi": "Luận văn tốt nghiệp", "sound_bridge": "Thì ra xích lại gần để xem luận văn tốt nghiệp xuất sắc.", "definition_en": "a long essay or dissertation involving personal research, written by a candidate for a degree", "example_en": "He is currently defending his doctoral thesis.", "example_vi": "Anh ấy hiện đang bảo vệ luận văn tiến sĩ của mình.", "page_number": 103},
      {"word_number": 280, "word": "Tutor", "phonetic": "/ˈtuː.t̬ɚ/", "word_type": "noun", "meaning_vi": "Gia sư, trợ giảng", "sound_bridge": "Tự tớ làm gia sư dạy kèm tiếng Anh cho các em nhỏ.", "definition_en": "a private teacher, typically one who teaches a single student or a very small group", "example_en": "Her tutor helped her improve her pronunciation.", "example_vi": "Gia sư đã giúp cô ấy cải thiện khả năng phát âm.", "page_number": 103}
    ]
  }
]

# Đọc Unit 1 đến 4 từ seed_units_1_to_4.py hoặc kết hợp lại
with open('backend/data/hacknao_vocab.json', 'r', encoding='utf-8') as f:
  vocab_1_to_4 = json.load(f)

vocab_5_to_10 = []
for u in units_5_to_10:
  for w in u["words"]:
    w["unit"] = u["unit"]
    w["unit_title"] = u["unit_title"]
    w["category"] = u["category"]
    w["status"] = "new"
    vocab_5_to_10.append(w)

all_vocab_1_to_10 = vocab_1_to_4 + vocab_5_to_10

with open('backend/data/hacknao_vocab.json', 'w', encoding='utf-8') as f:
  json.dump(all_vocab_1_to_10, f, ensure_ascii=False, indent=2)

print(f"✅ TỔNG CỘNG ĐÃ TỔNG HỢP XONG {len(all_vocab_1_to_10)} TỪ VỰNG CHUẨN XÁC 100% CHO CẢ 10 UNITS CỦA SÁCH HACK NÃO 1500!")
