import json
import os

unit1_vocabularies = [
  {
    "word_number": 1,
    "word": "Additional",
    "phonetic": "/əˈdɪʃ.ən.əl/",
    "word_type": "adjective",
    "meaning_vi": "Bổ sung, thêm vào",
    "sound_bridge": "A! Đích-sừn-nờ-ry bản bổ sung mới ra nè.",
    "definition_en": "more than was first mentioned or is usual",
    "example_en": "Your application still needs additional information.",
    "example_vi": "Đơn xin việc của bạn vẫn cần thêm thông tin bổ sung.",
    "unit": 1,
    "unit_title": "Communication 1",
    "category": "Communication",
    "page_number": 14,
    "status": "new"
  },
  {
    "word_number": 2,
    "word": "Admit",
    "phonetic": "/ədˈmɪt/",
    "word_type": "verb",
    "meaning_vi": "Thừa nhận",
    "sound_bridge": "Ăn mít không hết thì thừa nhận đi! Hỏng hết rồi lẽ ra phải cho vào tủ lạnh!",
    "definition_en": "to agree, often unwillingly, that something is true",
    "example_en": "I never admitted I did that.",
    "example_vi": "Tôi chưa bao giờ thừa nhận mình đã làm điều đó.",
    "unit": 1,
    "unit_title": "Communication 1",
    "category": "Communication",
    "page_number": 14,
    "status": "new"
  },
  {
    "word_number": 3,
    "word": "Agree",
    "phonetic": "/əˈɡriː/",
    "word_type": "verb",
    "meaning_vi": "Đồng ý",
    "sound_bridge": "Ơ con gà ri đi ăn mừng được đồng ý xuất chuồng kìa!",
    "definition_en": "to have the same opinion as somebody; to say that you have the same opinion",
    "example_en": "We can still work together if we don't agree.",
    "example_vi": "Chúng ta vẫn có thể làm việc cùng nhau nếu không đồng ý.",
    "unit": 1,
    "unit_title": "Communication 1",
    "category": "Communication",
    "page_number": 14,
    "status": "new"
  },
  {
    "word_number": 4,
    "word": "Announce",
    "phonetic": "/əˈnaʊns/",
    "word_type": "verb",
    "meaning_vi": "Thông báo",
    "sound_bridge": "Đi ăn nào, có thông báo nghỉ trưa rồi.",
    "definition_en": "to tell people something officially, especially about a decision, plans, etc",
    "example_en": "I'll announce the news tomorrow.",
    "example_vi": "Tôi sẽ thông báo tin tức vào ngày mai.",
    "unit": 1,
    "unit_title": "Communication 1",
    "category": "Communication",
    "page_number": 14,
    "status": "new"
  },
  {
    "word_number": 5,
    "word": "Apologize",
    "phonetic": "/əˈpɑː.lə.dʒaɪz/",
    "word_type": "verb",
    "meaning_vi": "Xin lỗi",
    "sound_bridge": "Cho mình xin lỗi nhé! Vừa ăn thịt bò mà nó dai quá nên rụng hết răng.",
    "definition_en": "to say that you are sorry for doing something wrong or causing a problem",
    "example_en": "I apologize for the inconvenience.",
    "example_vi": "Tôi xin lỗi vì sự bất tiện này.",
    "unit": 1,
    "unit_title": "Communication 1",
    "category": "Communication",
    "page_number": 15,
    "status": "new"
  },
  {
    "word_number": 6,
    "word": "Approve",
    "phonetic": "/əˈpruːv/",
    "word_type": "verb",
    "meaning_vi": "Tán thành, chấp thuận",
    "sound_bridge": "Ờ, ba rủ về quê và cả nhà đều tán thành.",
    "definition_en": "to think that somebody/something is good, acceptable or suitable",
    "example_en": "My boss approved the contract.",
    "example_vi": "Sếp tôi đã tán thành bản hợp đồng.",
    "unit": 1,
    "unit_title": "Communication 1",
    "category": "Communication",
    "page_number": 15,
    "status": "new"
  },
  {
    "word_number": 7,
    "word": "Argue",
    "phonetic": "/ˈɑːrɡ.juː/",
    "word_type": "verb",
    "meaning_vi": "Tranh luận, cãi nhau",
    "sound_bridge": "Ông suốt ngày chỉ biết ăn ngủ, tranh luận với ai được.",
    "definition_en": "to speak angrily to somebody because you disagree with them",
    "example_en": "I rarely argue with my brothers.",
    "example_vi": "Tôi hiếm khi tranh luận với các anh trai của mình.",
    "unit": 1,
    "unit_title": "Communication 1",
    "category": "Communication",
    "page_number": 15,
    "status": "new"
  },
  {
    "word_number": 8,
    "word": "Blame",
    "phonetic": "/bleɪm/",
    "word_type": "verb",
    "meaning_vi": "Khiển trách, đổ lỗi",
    "sound_bridge": "Bà lém thế sao Sếp khiển trách được, có khi lại được khen thưởng cũng nên.",
    "definition_en": "to think or say that somebody/something is responsible for something bad",
    "example_en": "Jack always blames others for his mistakes.",
    "example_vi": "Jack luôn đổ lỗi cho người khác về những sai lầm của mình.",
    "unit": 1,
    "unit_title": "Communication 1",
    "category": "Communication",
    "page_number": 15,
    "status": "new"
  },
  {
    "word_number": 9,
    "word": "Brief",
    "phonetic": "/briːf/",
    "word_type": "verb",
    "meaning_vi": "Tóm tắt, chỉ dẫn ngắn gọn",
    "sound_bridge": "Ríp tóm tắt câu chuyện trong 3 nốt nhạc.",
    "definition_en": "to give someone detailed instructions or information",
    "example_en": "I'll brief the staff before moving forward.",
    "example_vi": "Tôi sẽ tóm tắt cho các nhân viên trước khi tiếp tục.",
    "unit": 1,
    "unit_title": "Communication 1",
    "category": "Communication",
    "page_number": 15,
    "status": "new"
  },
  {
    "word_number": 10,
    "word": "Brochure",
    "phonetic": "/broʊˈʃʊr/",
    "word_type": "noun",
    "meaning_vi": "Cuốn sách nhỏ, tài liệu quảng cáo",
    "sound_bridge": "Bộ râu giả của sư phụ ở trong cuốn sách nhỏ.",
    "definition_en": "a small magazine or book containing pictures and information about something or advertising something",
    "example_en": "Take a look at our travel brochure!",
    "example_vi": "Hãy xem cuốn sách quảng cáo du lịch nhỏ của chúng tôi!",
    "unit": 1,
    "unit_title": "Communication 1",
    "category": "Communication",
    "page_number": 15,
    "status": "new"
  },
  {
    "word_number": 11,
    "word": "Certain",
    "phonetic": "/ˈsɜːr.tən/",
    "word_type": "adjective",
    "meaning_vi": "Chắc, chắc chắn",
    "sound_bridge": "Biết chắc là mình sai, anh ta sợ từng li từng tí.",
    "definition_en": "that you can rely on to happen or to be true",
    "example_en": "This means certain failure.",
    "example_vi": "Điều này đồng nghĩa với thất bại chắc chắn.",
    "unit": 1,
    "unit_title": "Communication 1",
    "category": "Communication",
    "page_number": 16,
    "status": "new"
  },
  {
    "word_number": 12,
    "word": "Comma",
    "phonetic": "/ˈkɑː.mə/",
    "word_type": "noun",
    "meaning_vi": "Dấu phẩy",
    "sound_bridge": "Con mà đặt dấu phẩy ở đây thì câu này sai nghĩa hoàn toàn đấy nhé.",
    "definition_en": "the mark (,) used to separate the items in a list or to show where there is a slight pause in a sentence",
    "example_en": "Use a comma when you're writing lists!",
    "example_vi": "Hãy sử dụng dấu phẩy khi bạn viết danh sách!",
    "unit": 1,
    "unit_title": "Communication 1",
    "category": "Communication",
    "page_number": 16,
    "status": "new"
  },
  {
    "word_number": 13,
    "word": "Complaint",
    "phonetic": "/kəmˈpleɪnt/",
    "word_type": "noun",
    "meaning_vi": "Lời phàn nàn, khiếu nại",
    "sound_bridge": "Ngày nào mấy con ma còn lên đây là ngày ấy có lời phàn nàn từ ông ta.",
    "definition_en": "a statement that something is wrong or not satisfactory",
    "example_en": "We've received a lot of complaints about your attitude.",
    "example_vi": "Chúng tôi đã nhận được rất nhiều lời phàn nàn về thái độ của bạn.",
    "unit": 1,
    "unit_title": "Communication 1",
    "category": "Communication",
    "page_number": 16,
    "status": "new"
  },
  {
    "word_number": 14,
    "word": "Complete",
    "phonetic": "/kəmˈpliːt/",
    "word_type": "verb",
    "meaning_vi": "Hoàn tất, hoàn thành",
    "sound_bridge": "Bữa cơm hôm nay không được hoàn tất vì cơm hết giữa chừng.",
    "definition_en": "to make whole or perfect",
    "example_en": "Complete your tasks on time!",
    "example_vi": "Hãy hoàn tất nhiệm vụ của bạn đúng hạn!",
    "unit": 1,
    "unit_title": "Communication 1",
    "category": "Communication",
    "page_number": 16,
    "status": "new"
  },
  {
    "word_number": 15,
    "word": "Conference",
    "phonetic": "/ˈkɑːn.fɚ.əns/",
    "word_type": "noun",
    "meaning_vi": "Hội nghị",
    "sound_bridge": "Hội nghị APEC lần này sẽ có cả cơm và phở phục vụ dần trong bữa tiệc.",
    "definition_en": "a large official meeting, usually lasting for a few days, at which people with the same work or interests come together to discuss their views",
    "example_en": "There's a big conference next week.",
    "example_vi": "Có một hội nghị lớn vào tuần tới.",
    "unit": 1,
    "unit_title": "Communication 1",
    "category": "Communication",
    "page_number": 16,
    "status": "new"
  },
  {
    "word_number": 16,
    "word": "Confirm",
    "phonetic": "/kənˈfɜːrm/",
    "word_type": "verb",
    "meaning_vi": "Xác nhận",
    "sound_bridge": "Việc đầu tiên trước khi đi xem phim là xác nhận xem còn phim không.",
    "definition_en": "to state or show that something is definitely true or correct, especially by providing evidence",
    "example_en": "Could you confirm some information for me?",
    "example_vi": "Bạn có thể xác nhận một số thông tin cho tôi được không?",
    "unit": 1,
    "unit_title": "Communication 1",
    "category": "Communication",
    "page_number": 16,
    "status": "new"
  },
  {
    "word_number": 17,
    "word": "Contact",
    "phonetic": "/ˈkɑːn.tækt/",
    "word_type": "verb",
    "meaning_vi": "Liên lạc",
    "sound_bridge": "Mẹ dặn: \"Đi công tác cũng nhớ liên lạc về nhà nhé con\".",
    "definition_en": "to communicate with somebody, especially regularly",
    "example_en": "Contact me when you arrive!",
    "example_vi": "Hãy liên lạc với tôi khi bạn đến nơi!",
    "unit": 1,
    "unit_title": "Communication 1",
    "category": "Communication",
    "page_number": 17,
    "status": "new"
  },
  {
    "word_number": 18,
    "word": "Convince",
    "phonetic": "/kənˈvɪns/",
    "word_type": "verb",
    "meaning_vi": "Thuyết phục",
    "sound_bridge": "Con vịt thuyết phục được con cá lên bờ chơi với nó.",
    "definition_en": "to make somebody/yourself believe that something is true",
    "example_en": "You can't convince me otherwise.",
    "example_vi": "Bạn không thể thuyết phục tôi nghĩ khác đi được.",
    "unit": 1,
    "unit_title": "Communication 1",
    "category": "Communication",
    "page_number": 17,
    "status": "new"
  },
  {
    "word_number": 19,
    "word": "Discuss",
    "phonetic": "/dɪˈskʌs/",
    "word_type": "verb",
    "meaning_vi": "Thảo luận",
    "sound_bridge": "Mọi người thảo luận cách đi cứu Sơn.",
    "definition_en": "to talk about something with somebody, especially in order to decide something",
    "example_en": "We'll discuss this later.",
    "example_vi": "Chúng ta sẽ thảo luận việc này sau.",
    "unit": 1,
    "unit_title": "Communication 1",
    "category": "Communication",
    "page_number": 17,
    "status": "new"
  },
  {
    "word_number": 20,
    "word": "Extreme",
    "phonetic": "/ɪkˈstriːm/",
    "word_type": "adjective",
    "meaning_vi": "Vô cùng, cực độ",
    "sound_bridge": "Ếch chê mèo yêu vô cùng.",
    "definition_en": "very great in degree",
    "example_en": "That's an extreme decision.",
    "example_vi": "Đó là một quyết định vô cùng mạo hiểm / cực đoan.",
    "unit": 1,
    "unit_title": "Communication 1",
    "category": "Communication",
    "page_number": 17,
    "status": "new"
  },
  {
    "word_number": 21,
    "word": "Hint",
    "phonetic": "/hɪnt/",
    "word_type": "noun",
    "meaning_vi": "Lời gợi ý",
    "sound_bridge": "Lời gợi ý ẩn chứa đằng sau bức hình, và bạn phải tìm ra nó.",
    "definition_en": "something that you say or do in an indirect way in order to show somebody what you are thinking",
    "example_en": "These hints may identify the killer.",
    "example_vi": "Những lời gợi ý này có thể nhận diện được kẻ sát nhân.",
    "unit": 1,
    "unit_title": "Communication 1",
    "category": "Communication",
    "page_number": 17,
    "status": "new"
  },
  {
    "word_number": 22,
    "word": "Hurry",
    "phonetic": "/ˈhɜːr.i/",
    "word_type": "verb",
    "meaning_vi": "Giục, vội vã",
    "sound_bridge": "Đừng giục tớ nữa, tớ đang hơ con chim ri, nó bị ướt hết người rồi.",
    "definition_en": "to do something more quickly than usual because there is not much time",
    "example_en": "You don't need to hurry. There is plenty of time.",
    "example_vi": "Bạn không cần phải vội. Vẫn còn rất nhiều thời gian.",
    "unit": 1,
    "unit_title": "Communication 1",
    "category": "Communication",
    "page_number": 17,
    "status": "new"
  },
  {
    "word_number": 23,
    "word": "Include",
    "phonetic": "/ɪnˈkluːd/",
    "word_type": "verb",
    "meaning_vi": "Bao gồm",
    "sound_bridge": "Công việc của Bin bao gồm cả việc in cái lu ra giấy A4.",
    "definition_en": "if one thing includes another, it has the second thing as one of its parts",
    "example_en": "I don't include my little brother when I invite my friends to play.",
    "example_vi": "Tôi không bao gồm em trai khi rủ bạn bè đến chơi.",
    "unit": 1,
    "unit_title": "Communication 1",
    "category": "Communication",
    "page_number": 18,
    "status": "new"
  },
  {
    "word_number": 24,
    "word": "Interact",
    "phonetic": "/ˌɪn.təˈrækt/",
    "word_type": "verb",
    "meaning_vi": "Tương tác",
    "sound_bridge": "Đi in tờ giấy về cách phân loại rác để dễ dàng xử lí là 1 cách kêu gọi mọi người cùng tương tác với nhau xây dựng cuộc sống màu xanh.",
    "definition_en": "to communicate with somebody, especially while you work, play or spend time with them",
    "example_en": "My cats don't like to interact.",
    "example_vi": "Mấy con mèo của tôi không thích tương tác.",
    "unit": 1,
    "unit_title": "Communication 1",
    "category": "Communication",
    "page_number": 18,
    "status": "new"
  },
  {
    "word_number": 25,
    "word": "Need",
    "phonetic": "/niːd/",
    "word_type": "verb",
    "meaning_vi": "Cần, cần có",
    "sound_bridge": "Nhu cầu của con nít là cần có thật nhiều đồ chơi.",
    "definition_en": "to require something/somebody because they are essential or very important, not just because you would like to have them",
    "example_en": "I need to get some sleep.",
    "example_vi": "Tôi cần phải ngủ một chút.",
    "unit": 1,
    "unit_title": "Communication 1",
    "category": "Communication",
    "page_number": 18,
    "status": "new"
  },
  {
    "word_number": 26,
    "word": "Order",
    "phonetic": "/ˈɔːr.dɚ/",
    "word_type": "verb",
    "meaning_vi": "Gọi món, đặt hàng",
    "sound_bridge": "Ô kìa, sao lại đơ người ra vậy. Gọi món đi!",
    "definition_en": "to ask for something to be made, supplied, or delivered, especially in a restaurant or shop",
    "example_en": "I'm going to order a pizza tonight.",
    "example_vi": "Tối nay tôi sẽ gọi một chiếc pizza.",
    "unit": 1,
    "unit_title": "Communication 1",
    "category": "Communication",
    "page_number": 18,
    "status": "new"
  },
  {
    "word_number": 27,
    "word": "Postcard",
    "phonetic": "/ˈpoʊst.kɑːrd/",
    "word_type": "noun",
    "meaning_vi": "Bưu thiếp",
    "sound_bridge": "Uống nước cho bớt khát rồi đi tặng bưu thiếp cho các bạn gái nhân ngày 8/3.",
    "definition_en": "a card used for sending messages by post without an envelope, especially one that has a picture on one side",
    "example_en": "Send me postcards when you're abroad.",
    "example_vi": "Hãy gửi bưu thiếp cho tôi khi bạn ở nước ngoài nhé.",
    "unit": 1,
    "unit_title": "Communication 1",
    "category": "Communication",
    "page_number": 18,
    "status": "new"
  },
  {
    "word_number": 28,
    "word": "Prepare",
    "phonetic": "/prɪˈper/",
    "word_type": "verb",
    "meaning_vi": "Chuẩn bị",
    "sound_bridge": "Trước khi đi xa, phải đi xe thì cần chuẩn bị kỹ lưỡng.",
    "definition_en": "to make something or somebody ready to be used or to do something",
    "example_en": "I still need to prepare my lesson plan.",
    "example_vi": "Tôi vẫn cần chuẩn bị giáo án bài giảng của mình.",
    "unit": 1,
    "unit_title": "Communication 1",
    "category": "Communication",
    "page_number": 18,
    "status": "new"
  },
  {
    "word_number": 29,
    "word": "Reason",
    "phonetic": "/ˈriː.zən/",
    "word_type": "noun",
    "meaning_vi": "Lý do",
    "sound_bridge": "Cán bộ đưa ra lý do di dân thật là nực cười.",
    "definition_en": "a cause or an explanation for something that has happened or that somebody has done",
    "example_en": "I have no reason to be upset, but I am.",
    "example_vi": "Tôi không có lý do gì để buồn bực, nhưng tôi vẫn thấy vậy.",
    "unit": 1,
    "unit_title": "Communication 1",
    "category": "Communication",
    "page_number": 19,
    "status": "new"
  },
  {
    "word_number": 30,
    "word": "Stamp",
    "phonetic": "/stæmp/",
    "word_type": "noun",
    "meaning_vi": "Con tem",
    "sound_bridge": "Nhân viên sợ con tem lấm lem sếp sẽ phạt.",
    "definition_en": "a small piece of paper with a design on it that you buy and stick on an envelope or a package before you post it",
    "example_en": "He collects old stamps.",
    "example_vi": "Anh ấy sưu tầm những con tem cũ.",
    "unit": 1,
    "unit_title": "Communication 1",
    "category": "Communication",
    "page_number": 19,
    "status": "new"
  },
  {
    "word_number": 31,
    "word": "Whole",
    "phonetic": "/hoʊl/",
    "word_type": "adjective",
    "meaning_vi": "Toàn bộ, tất cả",
    "sound_bridge": "Chính quyền hô hào toàn bộ người dân vùng lũ sơ tán.",
    "definition_en": "a complete thing",
    "example_en": "As a whole, the concert was a success.",
    "example_vi": "Nhìn chung toàn bộ, buổi hòa nhạc đã thành công rực rỡ.",
    "unit": 1,
    "unit_title": "Communication 1",
    "category": "Communication",
    "page_number": 19,
    "status": "new"
  }
]

with open('backend/data/hacknao_vocab.json', 'w', encoding='utf-8') as f:
    json.dump(unit1_vocabularies, f, ensure_ascii=False, indent=2)

print(f"Successfully saved {len(unit1_vocabularies)} vocabularies of Unit 1 into backend/data/hacknao_vocab.json")
